apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: piraeus-datastore-external-01b
resources:
  - basic.nvme.linstor-external-01b/
  # - burst.nvme.linstor-external-01b/
  # - sustain.nvme.linstor-external-01b/
  # - optane.nvme.linstor-external-01b/
