package codegen

import (
	"encoding/json"
	"fmt"
	"sort"
	"strings"
)

// Declarations renders a `.d.ts`-style block for the given namespaces. This is
// what `mcpx types` prints and what an agent pastes into its context: only the
// namespaces it asked for, nothing else.
func Declarations(nss []Namespace) string {
	var b strings.Builder
	b.WriteString("// Generated by mcpx. Call these from a script run with `mcpx run <file.ts>`.\n")
	b.WriteString("// Every function is async and returns the tool's result.\n\n")
	b.WriteString("type Attached<T, R = unknown> = T & { raw: R };\n\n")

	sort.Slice(nss, func(i, j int) bool { return nss[i].Name < nss[j].Name })
	for _, ns := range nss {
		b.WriteString(namespaceDoc(ns))
		fmt.Fprintf(&b, "declare namespace %s {\n", ns.Name)
		tools := append([]Tool(nil), ns.Tools...)
		sort.Slice(tools, func(i, j int) bool { return tools[i].Name < tools[j].Name })
		clash := funcCollisions(tools)
		for i, t := range tools {
			if i > 0 {
				b.WriteString("\n")
			}
			if names, ok := clash[ToolFuncName(t.Name)]; ok {
				// No declaration: either one would name the other's tool.
				fmt.Fprintf(&b, "  // %s: %s; use call(%s, name)\n", ToolFuncName(t.Name),
					sanitizeComment(collisionText(names)), quote(ns.Server))
				continue
			}
			b.WriteString(toolDecl(t, "  "))
		}
		b.WriteString("}\n\n")
	}
	return b.String()
}

// namespaceDoc renders the namespace description and the server's own
// instructions. The instructions are the only place conventions like "call
// list_pages first to get a pageId" are stated, so they belong next to the
// signatures rather than being discarded.
func namespaceDoc(ns Namespace) string {
	desc := strings.TrimSpace(ns.Description)
	prelude := strings.TrimSpace(ns.Prelude)
	instr := strings.TrimSpace(ns.Instructions)
	if desc == "" && prelude == "" && instr == "" {
		return ""
	}
	if prelude == "" && instr == "" {
		return "/** " + sanitizeComment(desc) + " */\n"
	}
	var b strings.Builder
	b.WriteString("/**\n")
	if desc != "" {
		b.WriteString(" * " + sanitizeComment(desc) + "\n *\n")
	}
	// The operator's prelude comes first: it is the more specific statement,
	// written by someone who knows what this deployment gets wrong.
	if prelude != "" {
		writeCommentBlock(&b, "Notes:", prelude)
	}
	if instr != "" {
		if prelude != "" {
			b.WriteString(" *\n")
		}
		writeCommentBlock(&b, "Server guidance:", instr)
	}
	b.WriteString(" */\n")
	return b.String()
}

func writeCommentBlock(b *strings.Builder, title, body string) {
	b.WriteString(" * " + title + "\n")
	for _, line := range strings.Split(body, "\n") {
		line = strings.TrimRight(line, " \t\r")
		if line == "" {
			b.WriteString(" *\n")
			continue
		}
		b.WriteString(" * " + sanitizeComment(line) + "\n")
	}
}

func toolDecl(t Tool, indent string) string {
	var b strings.Builder
	if d := strings.TrimSpace(t.Description); d != "" {
		lines := strings.Split(d, "\n")
		b.WriteString(indent + "/**\n")
		for _, l := range lines {
			b.WriteString(indent + " * " + sanitizeComment(l) + "\n")
		}
		b.WriteString(indent + " */\n")
	}
	argsType, optional := ArgsTypeFor(t.InputSchema, indent)
	resType := ResultTypeFor(t.OutputSchema, indent)
	opt := ""
	if optional {
		opt = "?"
	}
	fn := ToolFuncName(t.Name)
	fmt.Fprintf(&b, "%sfunction %s(args%s: %s): Promise<%s>;\n", indent, fn, opt, argsType, resType)
	return b.String()
}

// Module renders the importable client module. Scripts do:
//
//	import { fff, chrome_devtools } from "./.mcpx/client.ts";
//
// or use the default `tools` object. The module is written to disk, so the
// JavaScript runtime's own module cache applies and startup stays at tens of
// milliseconds.
func Module(nss []Namespace, endpoint, session string) string {
	var b strings.Builder
	b.WriteString(moduleHeader)
	fmt.Fprintf(&b, "const DEFAULT_ENDPOINT = %s;\n", quote(endpoint))
	fmt.Fprintf(&b, "const DEFAULT_SESSION = %s;\n\n", quote(session))
	b.WriteString(moduleRuntime)

	sort.Slice(nss, func(i, j int) bool { return nss[i].Name < nss[j].Name })

	for _, ns := range nss {
		tools := append([]Tool(nil), ns.Tools...)
		sort.Slice(tools, func(i, j int) bool { return tools[i].Name < tools[j].Name })

		b.WriteString(namespaceDoc(ns))
		fmt.Fprintf(&b, "export const %s = {\n", ns.Name)
		clash := funcCollisions(tools)
		done := map[string]bool{}
		for i, t := range tools {
			fn := ToolFuncName(t.Name)
			if names, ok := clash[fn]; ok {
				// One member that throws, naming every tool behind it,
				// instead of duplicate keys where the last silently won.
				if done[fn] {
					continue
				}
				done[fn] = true
				if i > 0 {
					b.WriteString("\n")
				}
				fmt.Fprintf(&b, "  get %s(): never {\n    throw new Error(%s);\n  },\n", fn,
					quote(ns.Name+"."+fn+": "+collisionText(names)+`; use call("`+ns.Server+`", name)`))
				continue
			}
			if i > 0 {
				b.WriteString("\n")
			}
			b.WriteString(toolImpl(ns.Server, t, "  "))
		}
		b.WriteString("};\n\n")
	}

	b.WriteString("export const tools = {\n")
	for _, ns := range nss {
		fmt.Fprintf(&b, "  %s,\n", ns.Name)
	}
	b.WriteString("};\n\n")
	b.WriteString(`Object.setPrototypeOf(tools, new Proxy({} as any, {
  get(_target, prop, _receiver) {
    for (const ns of Object.values(tools)) {
      if (typeof ns === "object" && ns !== null && typeof prop === "string" && prop in (ns as any)) {
        return (ns as any)[prop];
      }
    }
    if (typeof prop === "string" && prop !== "then" && prop !== "catch") {
      return (args: any) => __call("", prop, args ?? {});
    }
    return undefined;
  }
}));

`)

	// Metadata for search() and describe(), emitted as data rather than
	// reconstructed from the functions. A function cannot be asked what its
	// parameters are called once it is compiled, and the descriptions are
	// only in comments.
	b.WriteString(toolMeta(nss))
	b.WriteString("\nexport default tools;\n")
	return b.String()
}

func collisionText(names []string) string {
	q := make([]string, len(names))
	for i, n := range names {
		q[i] = fmt.Sprintf("%q", n)
	}
	return "tools " + strings.Join(q, " and ") + " both become this identifier"
}

// toolMeta renders what search and describe read.
func toolMeta(nss []Namespace) string {
	type meta struct {
		Description string   `json:"description"`
		Params      []string `json:"params"`
		Required    []string `json:"required"`
	}
	out := map[string]map[string]meta{}
	for _, ns := range nss {
		group := map[string]meta{}
		for _, t := range ns.Tools {
			params, required := schemaFields(t.InputSchema)
			group[t.Name] = meta{
				Description: firstLine(t.Description),
				Params:      params,
				Required:    required,
			}
		}
		out[ns.Name] = group
	}
	b, err := json.MarshalIndent(out, "", "  ")
	if err != nil {
		return "const __toolMeta: Record<string, Record<string, { description: string; params: string[]; required: string[] }>> = {};\n"
	}
	return "/** Parameter names and descriptions, for search() and describe(). */\n" +
		"const __toolMeta: Record<string, Record<string, { description: string; params: string[]; required: string[] }>> = " +
		string(b) + ";\n"
}

// schemaFields pulls parameter names out of a JSON Schema.
func schemaFields(raw json.RawMessage) (params, required []string) {
	// Never nil. A nil slice marshals to JSON null, and the emitted type
	// says string[] -- so one tool with no parameters made the generated
	// client fail to type check, and with it every script, whatever the
	// script said. "No parameters" is an empty list, not an absent one.
	params, required = []string{}, []string{}
	if len(raw) == 0 {
		return params, required
	}
	var doc struct {
		Properties map[string]any `json:"properties"`
		Required   []string       `json:"required"`
	}
	if json.Unmarshal(raw, &doc) != nil {
		return params, required
	}
	for k := range doc.Properties {
		params = append(params, k)
	}
	sort.Strings(params)
	if doc.Required != nil {
		required = doc.Required
	}
	sort.Strings(required)
	return params, required
}

func toolImpl(server string, t Tool, indent string) string {
	var b strings.Builder
	if d := strings.TrimSpace(t.Description); d != "" {
		lines := strings.Split(d, "\n")
		b.WriteString(indent + "/**\n")
		for _, l := range lines {
			b.WriteString(indent + " * " + sanitizeComment(l) + "\n")
		}
		b.WriteString(indent + " */\n")
	}
	argsType, optional := ArgsTypeFor(t.InputSchema, indent)
	resType := ResultTypeFor(t.OutputSchema, indent)
	opt := ""
	if optional {
		opt = "?"
	}
	fn := ToolFuncName(t.Name)
	fmt.Fprintf(&b, "%s%s(args%s: %s): Promise<%s> {\n", indent, fn, opt, argsType, resType)
	fmt.Fprintf(&b, "%s  return __call(%s, %s, args);\n", indent, quote(server), quote(t.Name))
	fmt.Fprintf(&b, "%s},\n", indent)
	return b.String()
}

const moduleHeader = `// Generated by mcpx. Do not edit; regenerated whenever tool schemas change.
//
// Each function posts one tools/call to the local mcpx daemon, which owns the
// MCP server processes. Results are returned already unwrapped: a text-only
// result becomes a string, a structured result becomes the parsed object.
// Reach for .raw on the returned value when you need the full MCP envelope.

`

const moduleRuntime = `function env(name: string): string {
  // Works on Deno, Bun and Node without assuming any of them.
  try {
    const d = (globalThis as any).Deno;
    if (d?.env?.get) return d.env.get(name) ?? "";
  } catch { /* permission denied: fall through */ }
  try {
    const p = (globalThis as any).process;
    if (p?.env) return p.env[name] ?? "";
  } catch { /* not Node-like */ }
  return "";
}

// The session and endpoint are read at run time rather than baked in, so that
// concurrent runs sharing one generated client file still get their own
// session. That isolation is what gives each run its own browser in
// session-mode pools.
const ENDPOINT = env("MCPX_ENDPOINT") || DEFAULT_ENDPOINT;
const SESSION = env("MCPX_SESSION") || DEFAULT_SESSION;

/**
 * The daemon's unix socket, when one is available.
 *
 * Measured against the same daemon: a warm socket answers in about 0.17ms,
 * loopback TCP in about 0.65ms. Small per call, but a script making a
 * thousand calls spends half a second on it, and the socket's filesystem
 * permissions are a better access control than an open port.
 *
 * Each runtime spells a unix-socket fetch differently -- Deno a custom HTTP
 * client, Bun an option on fetch, Node an agent on http -- so the choice is
 * made once here and every call goes through it. When none works, or no
 * socket is named, it falls back to the TCP endpoint every runtime supports.
 */
const SOCKET = env("MCPX_SOCKET");

type Fetcher = (url: string, init: RequestInit) => Promise<Response>;

const makeFetcher = (): { fetch: Fetcher; via: string } => {
  const g = globalThis as any;
  if (!SOCKET) return { fetch: (u, i) => fetch(u, i), via: "tcp" };

  // Deno: a client whose transport is the socket.
  if (g.Deno?.createHttpClient) {
    try {
      const client = g.Deno.createHttpClient({ proxy: { transport: "unix", path: SOCKET } });
      return { fetch: (u, i) => fetch(u, { ...i, client } as any), via: "unix" };
    } catch {
      /* an older Deno; fall through to TCP */
    }
  }
  // Bun: fetch takes the socket directly.
  if (g.Bun) {
    return { fetch: (u, i) => fetch(u, { ...i, unix: SOCKET } as any), via: "unix" };
  }
  // Node's fetch cannot address a socket without undici, which is not
  // guaranteed to be importable here. TCP is correct and nearly as fast.
  return { fetch: (u, i) => fetch(u, i), via: "tcp" };
};

const TRANSPORT = makeFetcher();

/** Where calls are going, for a script that wants to know. */
export const transport = (): string => TRANSPORT.via;

/** The base URL to put in front of a path, given the transport. */
const base = (): string => (TRANSPORT.via === "unix" ? "http://mcpx" : ENDPOINT);

/** A filesystem location, as given and as fully resolved. */
export interface PathPair {
  /** The path as mcpx was given it, symlinks and all. */
  readonly path: string;
  /** The same location with every symlink resolved. */
  readonly real: string;
}

function realpath(p: string): string {
  if (!p) return p;
  try {
    const d = (globalThis as any).Deno;
    if (d?.realPathSync) return d.realPathSync(p);
  } catch { /* not Deno, or denied */ }
  try {
    // Bun and Node both expose node:fs; require is available in Bun/CJS and
    // createRequire covers the rest without a static import.
    const req = (globalThis as any).require ??
      (globalThis as any).process?.getBuiltinModule?.bind((globalThis as any).process);
    const fs = req ? req("node:fs") : undefined;
    if (fs?.realpathSync) return fs.realpathSync(p);
  } catch { /* fall through */ }
  return p;
}

function pair(p: string): PathPair {
  return { path: p, real: realpath(p) };
}

function builtin(name: string): any {
  try {
    const g = globalThis as any;
    const req = g.require ?? g.process?.getBuiltinModule?.bind(g.process);
    return req ? req(name) : undefined;
  } catch {
    return undefined;
  }
}

function permissionDenied(kind: string, path?: string): Error {
  const target = path ? " " + String(path) : "";
  const err = new Error("Requires " + kind + " access" + target);
  (err as any).name = "PermissionDenied";
  return err;
}

function installDenoCompat(): void {
  const g = globalThis as any;
  const d = g.Deno ??= {};
  d.args ??= g.process?.argv?.slice(2) ?? [];
  if (typeof d.exit !== "function" && typeof g.process?.exit === "function") {
    d.exit = (code?: number) => g.process.exit(code);
  }
  if (!d.env?.get) {
    d.env = {
      get(name: string): string | undefined {
        return g.process?.env?.[name];
      },
    };
  }
  if (typeof d.inspect !== "function") {
    if (typeof g.Bun?.inspect === "function") {
      d.inspect = (v: unknown, opts?: { colors?: boolean; depth?: number }) =>
        g.Bun.inspect(v, opts);
    } else {
      const util = builtin("node:util");
      if (typeof util?.inspect === "function") {
        d.inspect = (v: unknown, opts?: { colors?: boolean; depth?: number }) =>
          util.inspect(v, { colors: false, depth: 4, ...opts });
      }
    }
  }
  if (typeof d.readTextFileSync !== "function") {
    d.readTextFileSync = (path: string): string => {
      if (env("MCPX_ALLOW_READ") !== "1") throw permissionDenied("read", path);
      const fs = builtin("node:fs");
      if (!fs?.readFileSync) throw new Error("readTextFileSync is unavailable in this runtime");
      return fs.readFileSync(path, "utf8");
    };
  }
  if (typeof d.readTextFile !== "function") {
    d.readTextFile = async (path: string): Promise<string> => {
      if (env("MCPX_ALLOW_READ") !== "1") throw permissionDenied("read", path);
      const fsp = builtin("node:fs/promises");
      if (typeof fsp?.readFile === "function") return await fsp.readFile(path, "utf8");
      return d.readTextFileSync(path);
    };
  }
}

function fromFileUrl(url: string): string {
  if (!url.startsWith("file://")) return url;
  const withoutScheme = decodeURIComponent(url.slice("file://".length));
  // file:///abs on unix; strip a leading host component if one is present.
  return withoutScheme.startsWith("/") ? withoutScheme : "/" + withoutScheme.replace(/^[^/]*\//, "");
}

/**
 * Where things are, from the point of view of any file in the import graph.
 *
 * These come from the environment rather than from module scope, so a script
 * three imports deep sees the same cwd and entry as the file the user
 * actually named. Use here(import.meta) for the current file.
 */
export const paths = {
  /** The directory the user ran mcpx from. */
  cwd: pair(env("MCPX_CWD")),
  /** The script mcpx was asked to run. Empty for mcpx exec. */
  entry: pair(env("MCPX_ENTRY")),
  /** This generated client module. */
  client: pair(env("MCPX_CLIENT")),
  /** The config file in effect, if any. */
  config: pair(env("MCPX_CONFIG_PATH")),
  /** Directories searched for named scripts, nearest first. */
  scriptDirs: (env("MCPX_SCRIPT_DIRS") || "").split(":").filter(Boolean),
};

/**
 * The file this is called from.
 *
 *     import { here } from "./mcpx-client.ts";
 *     const self = here(import.meta);   // { path, real }
 *
 * A module-level constant cannot do this: it would resolve once, in the
 * client, and every importer would see the client's own path.
 */
export function here(meta: { url: string }): PathPair {
  return pair(fromFileUrl(meta.url));
}

/** The directory containing the file this is called from. */
export function hereDir(meta: { url: string }): PathPair {
  const p = fromFileUrl(meta.url);
  const dir = p.slice(0, Math.max(0, p.lastIndexOf("/"))) || "/";
  return pair(dir);
}

export interface ContentBlock {
  type: string;
  text?: string;
  data?: string;
  mimeType?: string;
  uri?: string;
  [key: string]: unknown;
}

export interface RawToolResult {
  content?: ContentBlock[];
  structuredContent?: unknown;
  isError?: boolean;
  [key: string]: unknown;
}

export type Attached<T, R = RawToolResult> = T & { raw: R };

/**
 * The value a tool call resolves to.
 *
 * It behaves as the useful part of the result (parsed structured content, or
 * the concatenated text) while still carrying the full envelope on .raw.
 */
export type ToolResult = any;

/**
 * What mcpx worked out about a call a server refused: the argument at fault,
 * what changed in the tool's schema and when, and the smallest call that works.
 */
export interface Diagnostic {
  kind: string;
  tool?: string;
  field?: string;
  message: string;
  changed?: { when: string; kind: string; tool: string; field?: string; what: string };
  fix?: string;
  fatal?: boolean;
}

export class ToolError extends Error {
  // Written as plain fields rather than constructor parameter properties:
  // Node's type-stripping mode erases types without transforming code, and
  // parameter properties need a transform. Plain fields run everywhere.
  server: string;
  tool: string;
  raw?: unknown;
  diagnostics?: Diagnostic[];

  constructor(message: string, server: string, tool: string, raw?: unknown) {
    super(message);
    this.name = "ToolError";
    this.server = server;
    this.tool = tool;
    this.raw = raw;
  }
}

function attachRaw<T>(value: T, raw: RawToolResult): T {
  if (value !== null && typeof value === "object") {
    try {
      Object.defineProperty(value, "raw", { value: raw, enumerable: false, configurable: true });
    } catch { /* frozen object: leave it alone */ }
    return value;
  }
  // Primitives cannot carry properties; box strings so .raw still works.
  if (typeof value === "string") {
    const boxed = new String(value) as unknown as T;
    Object.defineProperty(boxed, "raw", { value: raw, enumerable: false, configurable: true });
    return boxed;
  }
  return value;
}

function unwrap(server: string, tool: string, raw: RawToolResult): ToolResult {
  if (raw && raw.isError) {
    const text = (raw.content ?? [])
      .filter((c) => c.type === "text" && typeof c.text === "string")
      .map((c) => c.text)
      .join("\n");
    throw new ToolError(text || ` + "`" + `${server}.${tool} returned isError` + "`" + `, server, tool, raw);
  }
  if (raw && raw.structuredContent !== undefined) {
    return attachRaw(raw.structuredContent as ToolResult, raw);
  }
  const blocks = raw?.content ?? [];
  const texts = blocks.filter((c) => c.type === "text" && typeof c.text === "string");
  if (texts.length === blocks.length && texts.length > 0) {
    const joined = texts.map((c) => c.text as string).join("\n");
    // Servers commonly return JSON as text; hand back the parsed value when
    // it parses cleanly, since that is almost always what the script wants.
    const t = joined.trim();
    if ((t.startsWith("{") && t.endsWith("}")) || (t.startsWith("[") && t.endsWith("]"))) {
      try {
        return attachRaw(JSON.parse(t) as ToolResult, raw);
      } catch { /* not JSON after all */ }
    }
    return attachRaw(joined as ToolResult, raw);
  }
  return attachRaw(blocks as ToolResult, raw);
}

async function __call(server: string, tool: string, args: unknown): Promise<ToolResult> {
  let resp: Response;
  try {
    resp = await TRANSPORT.fetch(base() + "/v1/call", {
      method: "POST",
      headers: {
        "content-type": "application/json",
        "x-mcpx-session": SESSION,
        "x-mcpx-call": SESSION,
        "x-mcpx-cwd": env("MCPX_CWD"),
        "x-mcpx-pid": env("MCPX_PID"),
        "x-mcpx-parent-session": env("MCPX_PARENT_SESSION_ID"),
        "x-mcpx-ephemeral": env("MCPX_EPHEMERAL"),
        "x-mcpx-run": env("MCPX_RUN"),
        "x-mcpx-input": env("MCPX_INPUT"),
      },
      body: JSON.stringify({ server, tool, args: args ?? {} }),
    });
  } catch (e) {
    throw new ToolError(
      ` + "`" + `cannot reach the mcpx daemon at ${ENDPOINT}: ${(e as Error).message}` + "`" + `,
      server,
      tool,
    );
  }
  const body = await resp.json().catch(() => ({ error: ` + "`" + `bad response (http ${resp.status})` + "`" + ` }));
  if (resp.status === 202 && body.inputRequired) {
    // The server stopped to ask something and nothing in this run can
    // answer it (MCPX_INPUT=report, set by mcpx exec and mcpx run). Exiting
    // 75 rather than throwing: a script that catches ToolError would
    // otherwise carry on as if the call had merely failed, and the caller
    // would never learn there is a question waiting.
    writeStderr("mcpx: " + String(body.inputRequired.text ?? "").trimEnd());
    const g = globalThis as any;
    if (typeof g.Deno?.exit === "function") g.Deno.exit(75);
    if (typeof g.process?.exit === "function") g.process.exit(75);
    throw new ToolError(` + "`" + `${server}.${tool} is waiting for input` + "`" + `, server, tool, body);
  }
  if (!resp.ok || body.error) {
    const err = new ToolError(body.error ?? ` + "`" + `http ${resp.status}` + "`" + `, server, tool, body);
    if (Array.isArray(body.diagnostics)) err.diagnostics = body.diagnostics;
    throw err;
  }
  return unwrap(server, tool, body.result as RawToolResult);
}

export type LogLevel = "debug" | "info" | "warn" | "error";

/** Structured values attached to a log record. */
export type LogAttrs = Record<string, unknown>;

const LOG_SENTINEL = "\u001emcpx\u001e";

const LEVEL_ORDER: Record<LogLevel, number> = { debug: 0, info: 1, warn: 2, error: 3 };

function levelFrom(name: string, fallback: number): number {
  const n = LEVEL_ORDER[name.trim().toLowerCase() as LogLevel];
  return n === undefined ? fallback : n;
}

// The active threshold, so a filtered call costs a comparison instead of a
// JSON encode and a write. The runner passes the same value it will filter on,
// which keeps the two ends from disagreeing.
const MIN_LEVEL = levelFrom(env("MCPX_LOG_LEVEL"), LEVEL_ORDER.info);

/**
 * Levels whose records carry a call site.
 *
 * Capture costs about 5 microseconds -- building the stack, not reading it --
 * which is roughly fifty times the cost of the record itself. Paying that on
 * every info line is waste; paying it on a warning is the moment you most want
 * to know where it came from. So the default traces warn and above, and
 * MCPX_LOG_SOURCE widens it to everything.
 */
const SOURCE_LEVELS: number = env("MCPX_LOG_SOURCE") === "1"
  ? LEVEL_ORDER.debug
  : env("MCPX_LOG_SOURCE") === "0"
  ? Number.POSITIVE_INFINITY
  : levelFrom(env("MCPX_LOG_SOURCE"), LEVEL_ORDER.warn);

function writeStderr(line: string): void {
  const d = (globalThis as any).Deno;
  if (d?.stderr?.writeSync) {
    d.stderr.writeSync(new TextEncoder().encode(line + "\n"));
    return;
  }
  const p = (globalThis as any).process;
  if (p?.stderr?.write) {
    p.stderr.write(line + "\n");
    return;
  }
  console.error(line);
}

/** A plain data object, as opposed to an Error, an array or a primitive. */
function isAttrs(v: unknown): v is LogAttrs {
  return typeof v === "object" && v !== null && !Array.isArray(v) &&
    !(v instanceof Error) && Object.getPrototypeOf(v) === Object.prototype;
}

function formatFrames(name: string, message: string, frames: Frame[]): string {
  const head = message ? name + ": " + message : name;
  const body = frames.map((f) => {
    const at = [f.file, f.line, f.column].filter((x) => x !== undefined).join(":");
    return "    at " + (f.function ? f.function + " (" + at + ")" : at);
  });
  return [head, ...body].join("\n");
}

function describeError(e: Error): LogAttrs {
  // Both forms are wanted: the string is what a human reads, the frames are
  // what a query groups by. They cannot both be taken from the Error, because
  // V8 memoises whatever prepareStackTrace returned the first time .stack is
  // touched -- ask for one and the other is gone. So frames are captured and
  // the string is rendered from them.
  const frames = errorFrames(e, 16);
  const stack = frames.length ? formatFrames(e.name, e.message, frames) : (
    typeof e.stack === "string" ? e.stack : ""
  );
  return {
    name: e.name,
    message: e.message,
    ...(stack ? { stack } : {}),
    ...(frames.length ? { frames } : {}),
    ...((e as any).cause !== undefined ? { cause: safeInspect((e as any).cause) } : {}),
  };
}

/** One frame of a captured stack. */
export interface Frame {
  file?: string;
  line?: number;
  column?: number;
  function?: string;
  type?: string;
  async?: boolean;
  native?: boolean;
}

/**
 * Capture a stack as structured frames.
 *
 * V8 exposes Error.prepareStackTrace, which hands back CallSite objects
 * instead of a formatted string. It is not in any standard, but Deno, Node and
 * Bun are all V8 or JSC-with-the-same-shim, and all three were verified to
 * support it. Parsing the string form is the fallback, and it is strictly
 * worse: it loses async and native flags and breaks on any path containing the
 * characters the format uses as delimiters.
 */
export function captureFrames(skip = 0, limit = 32): Frame[] {
  const E = Error as any;
  const previous = E.prepareStackTrace;
  const previousLimit = E.stackTraceLimit;
  try {
    E.stackTraceLimit = skip + limit + 4;
    E.prepareStackTrace = (_e: Error, sites: any[]) =>
      sites.map((s) => {
        const f: Frame = {};
        const file = s.getFileName?.();
        if (file) f.file = String(file).replace(/^file:\/\//, "");
        const line = s.getLineNumber?.();
        if (typeof line === "number") f.line = line;
        const col = s.getColumnNumber?.();
        if (typeof col === "number") f.column = col;
        const fn = s.getFunctionName?.();
        if (fn) f.function = fn;
        const tn = s.getTypeName?.();
        if (tn) f.type = tn;
        if (s.isAsync?.()) f.async = true;
        if (s.isNative?.()) f.native = true;
        return f;
      });
    const holder: any = {};
    E.captureStackTrace?.(holder, captureFrames);
    const frames: Frame[] = holder.stack ?? (new Error() as any).stack ?? [];
    return Array.isArray(frames) ? frames.slice(skip, skip + limit) : [];
  } catch {
    return [];
  } finally {
    E.prepareStackTrace = previous;
    E.stackTraceLimit = previousLimit;
  }
}

/** The frames of an Error, structured, without re-throwing it. */
export function errorFrames(err: Error, limit = 32): Frame[] {
  const E = Error as any;
  const previous = E.prepareStackTrace;
  try {
    E.prepareStackTrace = (_e: Error, sites: any[]) =>
      sites.map((s) => {
        const f: Frame = {};
        const file = s.getFileName?.();
        if (file) f.file = String(file).replace(/^file:\/\//, "");
        const line = s.getLineNumber?.();
        if (typeof line === "number") f.line = line;
        const fn = s.getFunctionName?.();
        if (fn) f.function = fn;
        if (s.isAsync?.()) f.async = true;
        return f;
      });
    // Reading .stack re-runs prepareStackTrace against the captured sites.
    const frames = (err as any).stack;
    return Array.isArray(frames) ? frames.slice(0, limit) : [];
  } catch {
    return [];
  } finally {
    E.prepareStackTrace = previous;
  }
}

/**
 * Where the call came from.
 *
 * Only called when the level warrants it, because capturing the stack is the
 * expensive half.
 */
function callSite(): LogAttrs | undefined {
  const frames = captureFrames(0, 8).filter((f) => !(f.file ?? "").includes("mcpx-client"));
  const top = frames[0];
  if (!top) return undefined;
  return {
    ...(top.file ? { "source.file": top.file } : {}),
    ...(top.line ? { "source.line": top.line } : {}),
    ...(top.column ? { "source.column": top.column } : {}),
    ...(top.function ? { "source.function": top.function } : {}),
  };
}

function send(kind: "log" | "result" | "artifact", payload: Record<string, unknown>): void {
  writeStderr(LOG_SENTINEL + JSON.stringify({ kind, ts: new Date().toISOString(), ...payload }));
}

function emitRecord(
  level: LogLevel,
  bound: LogAttrs,
  msg: string,
  rest: unknown[],
  fileOnly = false,
): void {
  // Short-circuit before any work. A debug call in a loop should cost a
  // comparison when nothing will print.
  const n = LEVEL_ORDER[level];
  if (n < MIN_LEVEL) return;

  let attrs: LogAttrs = { ...bound };
  const extra: unknown[] = [];
  for (const [i, v] of rest.entries()) {
    if (i === 0 && isAttrs(v)) {
      Object.assign(attrs, v);
      continue;
    }
    extra.push(v instanceof Error ? describeError(v) : v);
  }
  if (extra.length > 0) attrs.args = extra;
  if (n >= SOURCE_LEVELS) Object.assign(attrs, callSite());

  const hasTemplate = msg.includes("{");
  send("log", {
    level,
    msg,
    ...(hasTemplate ? { template: msg } : {}),
    ...(fileOnly ? { fileOnly: true } : {}),
    ...(Object.keys(attrs).length > 0 ? { attrs } : {}),
  });
}

/**
 * A logger, optionally carrying attributes bound by with().
 *
 * Callable directly: log("message") is log.info("message"), because the
 * overwhelmingly common case should not need a method name.
 */
export interface Logger {
  (msg: string, ...rest: unknown[]): void;
  debug(msg: string, ...rest: unknown[]): void;
  info(msg: string, ...rest: unknown[]): void;
  warn(msg: string, ...rest: unknown[]): void;
  error(msg: string, ...rest: unknown[]): void;
  /**
   * A logger carrying these attributes on every record, mirroring slog's
   * Logger.With.
   *
   * The returned logger must be passed where it is needed; JavaScript has no
   * ambient context, so bindings do not follow the call stack on their own.
   *
   *     const scoped = log.with({ run: runId });
   *     await scan(scoped, file);
   */
  with(attrs: LogAttrs): Logger;
  /** True when a record at this level would be emitted. */
  enabled(level: LogLevel): boolean;
}

function makeLogger(bound: LogAttrs): Logger {
  const fn = ((msg: string, ...rest: unknown[]) => emitRecord("info", bound, msg, rest)) as Logger;
  return Object.assign(fn, {
    debug: (msg: string, ...rest: unknown[]) => emitRecord("debug", bound, msg, rest),
    info: (msg: string, ...rest: unknown[]) => emitRecord("info", bound, msg, rest),
    warn: (msg: string, ...rest: unknown[]) => emitRecord("warn", bound, msg, rest),
    error: (msg: string, ...rest: unknown[]) => emitRecord("error", bound, msg, rest),
    with: (attrs: LogAttrs) => makeLogger({ ...bound, ...attrs }),
    enabled: (level: LogLevel) => LEVEL_ORDER[level] >= MIN_LEVEL,
  });
}

/**
 * Structured logging for scripts.
 *
 * A message may carry {placeholders} filled from the attributes, and {{x}}
 * writes a literal {x}:
 *
 *     log.info("fetched {count} pages in {ms}ms", { count: 3, ms: 412 });
 *
 * The first argument after the message is treated as attributes when it is a
 * plain object. Anything else, and anything after it, is collected into an
 * "args" array, so console-style calls still carry their values rather than
 * being dropped:
 *
 *     log.error("upload failed", err);            // err becomes args[0]
 *     log.debug("state", { id }, "extra", 42);    // id is an attribute
 *
 * Both the rendered message and its template are kept, so output reads as
 * prose and still groups by shape. stdout stays clear for results; this is
 * stderr.
 */
export const log: Logger = makeLogger({});

/**
 * Stream a result before the script finishes.
 *
 * A script's return value is one answer delivered at the end. emit() is for
 * many answers delivered as they are found: a long crawl, a per-file report, a
 * progress feed a caller can act on without waiting.
 *
 *     for (const file of files) emit({ file, findings: await scan(file) });
 *
 * Each value is written immediately. In ordinary use it lands on stdout as one
 * JSON line per call; under mcpx --json run the values are collected into
 * the envelope's results array in order. Either way the consumer sees them
 * in sequence rather than as one blob at the end.
 */
export function emitResult(value: unknown): void {
  send("result", { value });
}

export { emitResult as emit };

/**
 * Route console output through the record stream.
 *
 * console.log keeps going to stdout, because that is the script's result and
 * redirecting it would change what a caller reads. It is *also* mirrored as a
 * debug record so it lands in the durable log alongside everything else --
 * otherwise the one thing a script actually printed is the one thing missing
 * when you go looking afterwards.
 *
 * console.error/warn/info/debug become records outright: they are diagnostics,
 * and leaving them as bare stderr text means they miss enrichment, formatting
 * and the log file.
 */
export function captureConsole(): void {
  const c = globalThis.console as any;
  if (!c || c.__mcpxWrapped) return;
  const original: Record<string, ((...a: unknown[]) => void) | undefined> = {};
  for (const k of Object.keys(c)) {
    if (typeof c[k] === "function") original[k] = c[k].bind(c);
  }

  let depth = 0;

  // Render the message the way the runtime would have. A caller who wrote
  // console.info({a:1}) expects to read "{ a: 1 }", not the JSON encoding --
  // the structured copy of the value is already in args, so the message is
  // free to be the human form.
  const g = globalThis as any;
  const nodeInspect = builtin("node:util")?.inspect;
  const native: ((v: unknown) => string) | undefined =
    env("MCPX_RUNTIME") === "node" && typeof nodeInspect === "function"
      ? (v) => nodeInspect(v)
      : typeof g.Deno?.inspect === "function"
      ? (v) => g.Deno.inspect(v, { colors: false, depth: 4 })
      : typeof g.Bun?.inspect === "function"
      ? (v) => g.Bun.inspect(v)
      : typeof nodeInspect === "function"
      ? (v) => nodeInspect(v)
      : undefined;
  const one = (a: unknown) => {
    if (typeof a === "string") return a;
    if (native) {
      try {
        return native(a);
      } catch {
        /* fall through */
      }
    }
    return safeInspect(a);
  };
  // Format specifiers, because a script that writes console.info("%s: %d",
  // name, n) expects to read "alice: 42". Dropping the substitution and
  // printing the template beside its arguments is the kind of difference that
  // makes a captured console feel broken rather than redirected.
  //
  // Matches the runtimes: substitution happens only when there are arguments
  // to substitute, leftover specifiers stay as written, and surplus arguments
  // are appended.
  const FORMAT = /%[sdifjoOc%]/g;
  const applyFormat = (template: string, rest: unknown[]): [string, unknown[]] => {
    let i = 0;
    const text = template.replace(FORMAT, (spec) => {
      if (spec === "%%") return "%";
      if (i >= rest.length) return spec;
      const v = rest[i++];
      switch (spec) {
        case "%s":
          return typeof v === "string" ? v : one(v);
        case "%d":
        case "%i": {
          if (typeof v === "bigint") return String(v);
          const n = Number(v);
          return Number.isNaN(n) ? "NaN" : String(Math.trunc(n));
        }
        case "%f":
          return String(Number(v));
        case "%j":
          return safeInspect(v);
        case "%o":
        case "%O":
          return one(v);
        case "%c":
          // Styling has no meaning outside a browser. The argument is still
          // consumed, which is what keeps the remaining substitutions lined
          // up with their specifiers.
          return "";
      }
      return spec;
    });
    return [text, rest.slice(i)];
  };

  const render = (args: unknown[]) => {
    const pad = "  ".repeat(depth);
    if (args.length > 1 && typeof args[0] === "string" && FORMAT.test(args[0] as string)) {
      FORMAT.lastIndex = 0;
      const [text, rest] = applyFormat(args[0] as string, args.slice(1));
      return pad + [text, ...rest.map(one)].join(" ");
    }
    FORMAT.lastIndex = 0;
    return pad + args.map(one).join(" ");
  };

  // Keep the original name on every replacement. Something reading
  // console.info.name should still see "info"; losing it breaks introspection
  // for no gain.
  const patch = (name: string, fn: (...a: any[]) => void) => {
    Object.defineProperty(fn, "name", { value: name, configurable: true });
    c[name] = fn;
  };

  // The five that carry a level map onto it directly. console.info really is
  // log.info; there is no separate concept to reconcile.
  const direct: Record<string, LogLevel> = {
    info: "info",
    warn: "warn",
    error: "error",
    debug: "debug",
    dir: "info",
    dirxml: "info",
    table: "info",
  };
  for (const [name, level] of Object.entries(direct)) {
    patch(name, (...args: unknown[]) => emitRecord(level, { console: name }, render(args), []));
  }

  // stdout is the script's result, so console.log keeps going there. The
  // record exists so the durable log has it too, and is file-only so the
  // terminal does not show the same line twice.
  patch("log", (...args: unknown[]) => {
    original.log?.(...args);
    emitRecord("debug", { console: "log" }, render(args), [], true);
  });

  // console.trace is a stack request; honour it rather than dropping the part
  // that was asked for.
  patch("trace", (...args: unknown[]) => {
    emitRecord("debug", { console: "trace", frames: captureFrames(1, 16) }, render(args), []);
  });

  patch("assert", (cond: unknown, ...args: unknown[]) => {
    if (cond) return;
    emitRecord("error", { console: "assert" }, render(args.length ? args : ["assertion failed"]), []);
  });

  // Grouping is presentation, and a structured record has no nesting to show.
  // Indentation is preserved so output still reads as the author intended.
  patch("group", (...args: unknown[]) => {
    if (args.length) emitRecord("info", { console: "group" }, render(args), []);
    depth++;
  });
  // A record stream has nothing to collapse, so collapsed groups are groups.
  patch("groupCollapsed", (...args: unknown[]) => c.group(...args));
  patch("groupEnd", () => {
    depth = Math.max(0, depth - 1);
  });

  // indentLevel is a property rather than a method, and reading it is how some
  // libraries decide their own wrapping. Keep it truthful.
  Object.defineProperty(c, "indentLevel", {
    get: () => depth,
    set: (v: number) => {
      depth = Math.max(0, Math.trunc(Number(v) || 0));
    },
    configurable: true,
  });

  // console.clear wipes a terminal. It must not wipe a durable log, so the
  // request is recorded, the indent is reset, and the screen is left alone
  // unless nothing is capturing it.
  patch("clear", () => {
    depth = 0;
    emitRecord("debug", { console: "clear" }, "console.clear()", [], true);
  });

  // Devtools profiling markers. There is no profiler here, but dropping the
  // call silently loses a deliberate annotation, so they become records.
  for (const name of ["profile", "profileEnd", "timeStamp"]) {
    patch(name, (...args: unknown[]) => {
      emitRecord("debug", { console: name }, render(args.length ? args : [name + "()"]), [], true);
    });
  }

  const counters = new Map<string, number>();
  patch("count", (label = "default") => {
    const n = (counters.get(label) ?? 0) + 1;
    counters.set(label, n);
    emitRecord("debug", { console: "count", label, count: n }, label + ": " + n, []);
  });
  patch("countReset", (label = "default") => {
    counters.delete(label);
  });

  const timers = new Map<string, number>();
  patch("time", (label = "default") => {
    timers.set(label, performance.now());
  });
  patch("timeLog", (label = "default", ...args: unknown[]) => {
    const started = timers.get(label);
    if (started === undefined) return;
    const ms = performance.now() - started;
    emitRecord("debug", { console: "timeLog", label, ms },
      label + ": " + ms.toFixed(3) + "ms " + render(args), []);
  });
  patch("timeEnd", (label = "default") => {
    const started = timers.get(label);
    if (started === undefined) return;
    timers.delete(label);
    const ms = performance.now() - started;
    emitRecord("debug", { console: "timeEnd", label, ms },
      label + ": " + ms.toFixed(3) + "ms", []);
  });

  c.__mcpxWrapped = true;
  c.__mcpxOriginal = original;
}

/** Undo captureConsole, for a script that wants the real console back. */
export function releaseConsole(): void {
  const c = globalThis.console as any;
  if (!c?.__mcpxWrapped) return;
  for (const [k, fn] of Object.entries(c.__mcpxOriginal ?? {})) {
    if (fn) c[k] = fn;
  }
  delete c.__mcpxWrapped;
  delete c.__mcpxOriginal;
}

function safeInspect(v: unknown): string {
  if (v instanceof Error) return v.stack ?? String(v);
  try {
    return JSON.stringify(v) ?? String(v);
  } catch {
    return String(v);
  }
}

/**
 * Put the standard surface on globalThis.
 *
 * A script that imports is easier to read and gives an editor something to
 * work with; a script written like a shell one-liner should not have to. Both
 * work: the launcher installs these before importing the module, and the
 * generated declarations tell an editor they exist.
 */
/** One tool, as search returns it. */
export interface ToolMatch {
  namespace: string;
  tool: string;
  /** Call it as tools[namespace][tool](args). */
  call: (args?: Record<string, unknown>) => Promise<ToolResult>;
  description: string;
  /** Parameter names, so a caller can check before invoking. */
  params: string[];
  required: string[];
}

/**
 * Find tools by name or description, from inside a script.
 *
 * Without this, discovering a tool means ending the script, running
 * "mcpx search", reading the result, and writing a new script. That round
 * trip is the expensive part -- for a model it is a whole turn, and the
 * intermediate result passes through its context on the way.
 *
 * Synchronous, because everything it searches is already in this file. A
 * promise here would only be a promise of work already done.
 */
export function search(query: string, limit = 20): ToolMatch[] {
  const words = String(query).toLowerCase().split(/\s+/).filter(Boolean);
  if (words.length === 0) return [];

  const scored: Array<{ score: number; match: ToolMatch }> = [];
  for (const [ns, group] of Object.entries(tools)) {
    for (const [name, fn] of Object.entries(group as Record<string, unknown>)) {
      if (typeof fn !== "function") continue;
      const meta = __toolMeta[ns]?.[name] ?? { description: "", params: [], required: [] };
      const hay = (ns + " " + name + " " + meta.description).toLowerCase();

      let score = 0;
      for (const w of words) {
        if (!hay.includes(w)) {
          score = -1;
          break;
        }
        // A word in the name is worth more than a word in the prose. A tool
        // called "grep" beats one whose description merely mentions grepping.
        score += (ns + " " + name).toLowerCase().includes(w) ? 10 : 1;
      }
      if (score < 0) continue;
      scored.push({
        score,
        match: {
          namespace: ns,
          tool: name,
          call: fn as ToolMatch["call"],
          description: meta.description,
          params: meta.params,
          required: meta.required,
        },
      });
    }
  }
  scored.sort((a, b) => b.score - a.score || a.match.tool.localeCompare(b.match.tool));
  return scored.slice(0, limit).map((s) => s.match);
}

/**
 * The signature of one tool, or of a whole namespace.
 *
 * The companion to search: found something, now what does it take. Returns
 * text because that is what it is for -- reading, or printing when a script
 * is exploring rather than doing.
 */
export function describe(name: string): string {
  const parts = String(name).split(".");
  const ns = parts[0];
  const tool = parts[1];
  const group = __toolMeta[ns];
  if (!group) {
    return "no namespace " + JSON.stringify(ns) +
      "; there is " + Object.keys(tools).join(", ");
  }
  const render = (t: string): string => {
    const m = group[t];
    if (!m) return "  " + t + "(...)";
    const args = m.params
      .map((p) => (m.required.indexOf(p) >= 0 ? p : p + "?"))
      .join(", ");
    const head = "  " + ns + "." + t + "({ " + args + " })";
    return m.description ? head + "\n      " + m.description : head;
  };
  if (!tool) {
    return Object.keys(group).sort().map(render).join("\n");
  }
  return render(tool);
}

export function installGlobals(): void {
  const g = globalThis as any;
  installDenoCompat();
  g.log ??= log;
  g.emit ??= emitResult;
  g.tools ??= tools;
  g.call ??= call;
  g.batch ??= batch;
  g.readResource ??= readResource;
  g.artifact ??= artifact;
  g.ToolError ??= ToolError;
  g.paths ??= paths;
  g.here ??= here;
  g.hereDir ??= hereDir;
  g.releaseConsole ??= releaseConsole;
  g.captureFrames ??= captureFrames;
  g.errorFrames ??= errorFrames;
  g.search ??= search;
  g.transport ??= transport;
  g.describe ??= describe;
  for (const [name, ns] of Object.entries(tools)) {
    g[name] ??= ns;
    if (typeof ns === "object" && ns !== null) {
      for (const [fnName, fn] of Object.entries(ns)) g[fnName] ??= fn;
    }
  }
}

/** Call any tool by name, including ones added after this client was generated. */
export async function call(serverOrTool: string, toolOrArgs?: any, args?: unknown): Promise<ToolResult> {
  if (arguments.length === 1 || (arguments.length === 2 && (typeof toolOrArgs === "object" || toolOrArgs === undefined))) {
    return __call("", serverOrTool, toolOrArgs ?? {});
  }
  return __call(serverOrTool, String(toolOrArgs), args ?? {});
}

/** Execute multiple tool calls in a single turn. */
export async function batch(
  calls: Array<{ server?: string; namespace?: string; tool: string; args?: unknown; arguments?: unknown }>,
  options?: { stopOnError?: boolean; parallel?: boolean }
): Promise<Array<{ index: number; server?: string; tool: string; status: string; result?: any; error?: string; isError?: boolean }>> {
  const resp = await TRANSPORT.fetch(base() + "/v1/batch", {
    method: "POST",
    headers: {
      "content-type": "application/json",
      "x-mcpx-session": SESSION,
      "x-mcpx-call": SESSION,
      "x-mcpx-cwd": env("MCPX_CWD"),
      "x-mcpx-pid": env("MCPX_PID"),
      "x-mcpx-parent-session": env("MCPX_PARENT_SESSION_ID"),
    },
    body: JSON.stringify({
      calls: calls.map((c) => ({
        server: c.server ?? c.namespace ?? "",
        tool: c.tool,
        args: c.args ?? c.arguments ?? {},
      })),
      stopOnError: options?.stopOnError ?? true,
      parallel: options?.parallel ?? false,
    }),
  });
  const body = await resp.json();
  if (!resp.ok || body.error) throw new Error(body.error ?? ("http " + resp.status));
  return body.results ?? [];
}

/** Read an MCP resource URI. */
export async function readResource(server: string, uri: string): Promise<ToolResult> {
  const resp = await TRANSPORT.fetch(base() + "/v1/resource", {
    method: "POST",
    headers: {
      "content-type": "application/json",
      "x-mcpx-session": SESSION,
      "x-mcpx-call": SESSION,
      "x-mcpx-cwd": env("MCPX_CWD"),
      "x-mcpx-pid": env("MCPX_PID"),
      "x-mcpx-parent-session": env("MCPX_PARENT_SESSION_ID"),
    },
    body: JSON.stringify({ server, uri }),
  });
  const body = await resp.json();
  if (!resp.ok || body.error) throw new ToolError(body.error ?? ` + "`" + `http ${resp.status}` + "`" + `, server, uri);
  return body.result;
}

/** What artifact() hands back. Small on purpose: no bytes. */
export interface ArtifactRef {
  /** The random handle the artifact is fetched by. */
  readonly id: string;
  /** The sanitised name. It may differ from what was asked for. */
  readonly name: string;
  /** mcpx://artifacts/<id>, readable as an MCP resource. */
  readonly uri: string;
  readonly size: number;
  readonly mime: string;
  readonly sha256: string;
}

export interface ArtifactOptions {
  /** Overrides the type guessed from the name. */
  mime?: string;
  /** How long to keep it, as a Go duration string. Default from settings. */
  ttl?: string;
}

/**
 * Hand a file back to whoever asked for this run.
 *
 *     const shot = await chrome_devtools.take_screenshot({ format: "png" });
 *     await artifact("checkout.png", shot);
 *     return { total };
 *
 * The data may be a string, bytes, an ArrayBuffer, { path } for a file
 * already on disk, or an MCP image/audio/resource content item straight from
 * a tool result.
 *
 * This behaves identically wherever the script runs, and that is the whole
 * point of it. Locally the daemon hardlinks the file it was pointed at.
 * Remotely the bytes travel once, to the daemon, and the caller fetches them
 * only if it wants them. The script does not ask which case it is in, because
 * a script that has to ask is a script with two code paths and one of them is
 * never tested.
 */
export async function artifact(
  name: string,
  data: string | Uint8Array | ArrayBuffer | { path: string } | ContentBlock | { raw?: RawToolResult },
  opts?: ArtifactOptions,
): Promise<ArtifactRef> {
  const norm = normaliseArtifact(data);
  const query = new URLSearchParams({ name });
  if (opts?.mime ?? norm.mime) query.set("mime", (opts?.mime ?? norm.mime) as string);
  if (opts?.ttl) query.set("ttl", opts.ttl);
  const run = env("MCPX_RUN");
  if (run) query.set("run", run);
  if (SESSION) query.set("session", SESSION);

  const headers: Record<string, string> = { "x-mcpx-session": SESSION };
  // Only when it is actually known. Sending the generic type would beat the
  // daemon's guess from the extension, and "shot.png" is a better source of
  // truth than "some bytes".
  const declared = opts?.mime ?? norm.mime;
  if (declared) headers["content-type"] = declared;
  let body: BodyInit | undefined;
  if (norm.path !== undefined && env("MCPX_ARTIFACTS_LOCAL") === "1") {
    // The daemon can see this file. Naming it lets the store hardlink rather
    // than read, hash into memory and write again.
    headers["x-mcpx-path"] = norm.path;
  } else if (norm.path !== undefined) {
    body = await readFileBytes(norm.path) as unknown as BodyInit;
  } else {
    body = norm.bytes as unknown as BodyInit;
  }

  const resp = await TRANSPORT.fetch(base() + "/v1/artifacts?" + query.toString(), {
    method: "POST",
    headers,
    body,
  });
  const out = await resp.json();
  if (!resp.ok || out.error) {
    throw new Error("artifact " + JSON.stringify(name) + ": " + (out.error ?? "http " + resp.status));
  }
  // Announced on the same channel as log and emit, so a consumer watching a
  // run learns the artifact exists while it is still running rather than at
  // the end.
  send("artifact", { id: out.id, name: out.name });
  return out as ArtifactRef;
}

type NormalisedArtifact = { bytes?: Uint8Array; path?: string; mime?: string };

function b64ToBytes(b64: string): Uint8Array {
  const bin = atob(b64);
  const out = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) out[i] = bin.charCodeAt(i);
  return out;
}

async function readFileBytes(path: string): Promise<Uint8Array> {
  const d = (globalThis as any).Deno;
  if (typeof d?.readFile === "function") return await d.readFile(path);
  const fsp = builtin("node:fs/promises");
  if (typeof fsp?.readFile === "function") return new Uint8Array(await fsp.readFile(path));
  throw new Error("cannot read " + path + " in this runtime");
}

/**
 * Reduce whatever was passed to bytes or a path.
 *
 * Accepting an MCP content item directly is what makes the common case one
 * line: a screenshot arrives as { type: "image", data, mimeType } and that is
 * exactly what gets passed in, with no unwrapping at the call site.
 */
function normaliseArtifact(data: unknown): NormalisedArtifact {
  if (typeof data === "string") {
    return { bytes: new TextEncoder().encode(data), mime: "text/plain; charset=utf-8" };
  }
  if (data instanceof Uint8Array) return { bytes: data };
  if (data instanceof ArrayBuffer) return { bytes: new Uint8Array(data) };
  if (ArrayBuffer.isView(data)) {
    const v = data as ArrayBufferView;
    return { bytes: new Uint8Array(v.buffer, v.byteOffset, v.byteLength) };
  }
  if (data && typeof data === "object") {
    const o = data as Record<string, any>;
    if (typeof o.path === "string") return { path: o.path };
    // A tool result carries its envelope on .raw; reach through to a content
    // block with a body rather than making every call site do it. Media and
    // embedded resources first: a screenshot result is a caption followed by
    // the image, and the caption is not the file anyone meant.
    if (o.raw && typeof o.raw === "object") {
      const blocks = (o.raw as RawToolResult).content ?? [];
      for (const b of blocks) {
        const inner = b?.type === "text" ? undefined : normaliseContent(b);
        if (inner) return inner;
      }
      for (const b of blocks) {
        const inner = normaliseContent(b);
        if (inner) return inner;
      }
    }
    const direct = normaliseContent(o as ContentBlock);
    if (direct) return direct;
  }
  // Anything else is a value, and a value's file form is its JSON.
  return {
    bytes: new TextEncoder().encode(JSON.stringify(data, null, 2)),
    mime: "application/json",
  };
}

function normaliseContent(b: ContentBlock | undefined): NormalisedArtifact | undefined {
  if (!b || typeof b !== "object") return undefined;
  if ((b.type === "image" || b.type === "audio") && typeof b.data === "string") {
    return { bytes: b64ToBytes(b.data), mime: b.mimeType };
  }
  if (b.type === "resource") {
    const r = (b as any).resource;
    if (r && typeof r.blob === "string") return { bytes: b64ToBytes(r.blob), mime: r.mimeType };
    if (r && typeof r.text === "string") {
      return { bytes: new TextEncoder().encode(r.text), mime: r.mimeType ?? "text/plain" };
    }
  }
  if (b.type === "text" && typeof b.text === "string") {
    return { bytes: new TextEncoder().encode(b.text), mime: "text/plain; charset=utf-8" };
  }
  return undefined;
}

`

// GlobalDeclarations emits ambient declarations for the surface the launcher
// installs on globalThis.
//
// It exists for editors. A script written like a one-liner calls log() and
// emit() without importing them, which is convenient and, without this file,
// invisible to a language server. Generating it costs nothing and turns an
// undefined-name squiggle into completion.
func GlobalDeclarations(nss []Namespace) string {
	var b strings.Builder
	b.WriteString("// Generated by mcpx. Ambient declarations for the globals the runner\n")
	b.WriteString("// installs. Importing from ./" + "mcpx-client.ts" + " works too and is equivalent.\n\n")
	b.WriteString("import type { Logger, LogAttrs, PathPair, ToolResult } from \"./mcpx-client.ts\";\n")
	b.WriteString("import type * as __mcpx from \"./mcpx-client.ts\";\n\n")
	b.WriteString("declare global {\n")
	b.WriteString("  /** Structured logging. Callable: log(msg) is log.info(msg). */\n")
	b.WriteString("  const log: Logger;\n")
	b.WriteString("  /** Stream a result before the script finishes. */\n")
	b.WriteString("  const emit: (value: unknown) => void;\n")
	b.WriteString("  /** Call any tool by name. */\n")
	b.WriteString("  const call: typeof __mcpx.call;\n")
	b.WriteString("  /** Execute multiple tool calls in a single turn. */\n")
	b.WriteString("  const batch: typeof __mcpx.batch;\n")
	b.WriteString("  const readResource: typeof __mcpx.readResource;\n")
	b.WriteString("  /** Hand a file back to whoever asked for this run. */\n")
	b.WriteString("  const artifact: typeof __mcpx.artifact;\n")
	b.WriteString("  const ToolError: typeof __mcpx.ToolError;\n")
	b.WriteString("  const paths: typeof __mcpx.paths;\n")
	b.WriteString("  const here: typeof __mcpx.here;\n")
	b.WriteString("  const hereDir: typeof __mcpx.hereDir;\n")
	b.WriteString("  /** Find tools by name or description, without leaving the script. */\n")
	b.WriteString("  const search: typeof __mcpx.search;\n")
	b.WriteString("  /** The signature of one tool (\"ns.tool\") or of a namespace. */\n")
	b.WriteString("  const describe: typeof __mcpx.describe;\n")
	b.WriteString("  const transport: typeof __mcpx.transport;\n")
	b.WriteString("  const captureFrames: typeof __mcpx.captureFrames;\n")
	b.WriteString("  const errorFrames: typeof __mcpx.errorFrames;\n")
	b.WriteString("  const releaseConsole: typeof __mcpx.releaseConsole;\n")
	b.WriteString("  const tools: typeof __mcpx.tools;\n")

	sorted := append([]Namespace(nil), nss...)
	sort.Slice(sorted, func(i, j int) bool { return sorted[i].Name < sorted[j].Name })
	for _, ns := range sorted {
		if ns.Description != "" {
			b.WriteString("  /** " + sanitizeComment(ns.Description) + " */\n")
		}
		fmt.Fprintf(&b, "  const %s: typeof __mcpx.%s;\n", ns.Name, ns.Name)
	}
	b.WriteString("}\n\nexport {};\n")
	return b.String()
}
