package api

import (
	"fmt"
	"sort"
	"strings"
)

// PluginTS renders plugin/opencode/mcpx/ops.gen.ts: one typed method per
// /v1 operation, for the opencode plugin's DaemonClient.
//
// Generated for the reason the MCP tools and the CLI commands are: the
// plugin's hand-written methods covered twenty of the operations in this
// table -- docs/parity.md is generated from it and names which -- and one of
// the twenty, call(), sent its arguments under a key the route does not
// read, so every tool it called received none. A method built from the
// declaration cannot name a parameter the route does not take, and the type
// checker holds every caller to the same names.
func PluginTS() string {
	ops := Ops()
	sort.Slice(ops, func(i, j int) bool { return ops[i].Name < ops[j].Name })

	var b strings.Builder
	b.WriteString(`// Code generated by mcpx from internal/api, the /v1 operation table. DO NOT EDIT.
// Regenerate with: go test ./internal/api -run TestPluginOpsAreGenerated -update
//
// One typed method per operation. The request is assembled from the same
// declaration the daemon's routes, the MCP tools and the CLI commands are, so
// a parameter this file sends is one the route reads.

/** Where a parameter travels. */
type In = "path" | "query" | "body"

type ParamSpec = { in: In; required?: boolean; raw?: boolean }

type OpSpec = {
  method: string
  path: string
  params: Record<string, ParamSpec>
  /** The body parameter that is the whole body, for routes that take a bare document. */
  wrap?: string
  /** json is parsed; response is handed back for the caller to read as text, bytes or a stream. */
  response: "json" | "response"
}

/** Every /v1 operation, by name. */
export const OPS: Record<string, OpSpec> = {
`)
	for _, op := range ops {
		fmt.Fprintf(&b, "  %s: {\n    method: %q,\n    path: %q,\n    params: {", op.Name, op.Method, op.Path)
		if len(op.Params) == 0 {
			b.WriteString("},\n")
		} else {
			b.WriteString("\n")
			for _, p := range op.Params {
				fmt.Fprintf(&b, "      %s: { in: %q", p.Name, string(p.In))
				if p.Required {
					b.WriteString(", required: true")
				}
				if p.Raw {
					b.WriteString(", raw: true")
				}
				b.WriteString(" },\n")
			}
			b.WriteString("    },\n")
		}
		if w, ok := op.bodyIsOneObject(); ok {
			fmt.Fprintf(&b, "    wrap: %q,\n", w)
		}
		resp := "json"
		if op.Text || op.Streams {
			resp = "response"
		}
		fmt.Fprintf(&b, "    response: %q,\n  },\n", resp)
	}
	b.WriteString(`}

/** A refusal from the daemon, with the status and the body kept. */
export class OpError extends Error {
  constructor(
    readonly op: string,
    readonly status: number,
    readonly body: string,
  ) {
    let msg = body.trim()
    try {
      const parsed = JSON.parse(body) as { error?: unknown }
      if (typeof parsed.error === "string" && parsed.error) msg = parsed.error
    } catch {
      // Not JSON; the text is the message.
    }
    super(` + "`mcpx ${op}: ${status}: ${msg}`" + `)
  }
}

const scalar = (v: unknown): string => {
  if (typeof v === "string") return v
  if (typeof v === "boolean") return v ? "1" : "0"
  if (typeof v === "number") return String(v)
  return JSON.stringify(v)
}

/**
 * The path and request for one operation. The same rules as the Go side's
 * Op.Request: path parameters are escaped into the path, query parameters
 * are scalars, a raw parameter is the body as bytes, and everything else is
 * a JSON object -- or, for the routes that take a bare document, that
 * document.
 */
export const buildRequest = (name: string, args: Record<string, unknown> = {}): { path: string; init: RequestInit } => {
  const spec = OPS[name]
  if (!spec) throw new Error(` + "`mcpx: no operation ${name}`" + `)
  let path = spec.path
  const query = new URLSearchParams()
  const body: Record<string, unknown> = {}
  let raw: BodyInit | undefined
  for (const [key, value] of Object.entries(args)) {
    if (value === undefined) continue
    const p = spec.params[key]
    if (!p) throw new Error(` + "`mcpx ${name} takes no argument ${key}`" + `)
    if (p.raw) raw = value as BodyInit
    else if (p.in === "path") path = path.replace(` + "`{${key}}`" + `, encodeURIComponent(scalar(value)))
    else if (p.in === "query") {
      const s = scalar(value)
      if (s !== "") query.set(key, s)
    } else body[key] = value
  }
  for (const [key, p] of Object.entries(spec.params)) {
    if (p.required && args[key] === undefined) throw new Error(` + "`mcpx ${name}: ${key} is required`" + `)
  }
  if (path.includes("{")) throw new Error(` + "`mcpx ${name}: unfilled path parameter in ${path}`" + `)
  const qs = query.toString()
  if (qs) path += "?" + qs
  const init: RequestInit = { method: spec.method }
  if (raw !== undefined) {
    init.body = raw
    init.headers = { "content-type": "application/octet-stream" }
  } else if (spec.method !== "GET") {
    const doc = spec.wrap ? (body[spec.wrap] ?? {}) : body
    init.body = JSON.stringify(doc)
    init.headers = { "content-type": "application/json" }
  }
  return { path, init }
}

/** Sends one request to the daemon; DaemonClient.raw is one. */
export type Fetcher = (path: string, init: RequestInit) => Promise<Response>

/** Options every method accepts. */
export type CallOptions = { signal?: AbortSignal }

/** A typed method for every /v1 operation. */
export class DaemonOps {
  constructor(private readonly fetcher: Fetcher) {}

  /** Performs any operation by name; the typed methods below are this. */
  async invoke(name: string, args: Record<string, unknown> = {}, opts: CallOptions = {}): Promise<unknown> {
    const { path, init } = buildRequest(name, args)
    if (opts.signal) init.signal = opts.signal
    const res = await this.fetcher(path, init)
    if (!res.ok) throw new OpError(name, res.status, await res.text())
    if (OPS[name].response === "response") return res
    const text = await res.text()
    return text ? JSON.parse(text) : undefined
  }
`)
	for _, op := range ops {
		b.WriteString("\n")
		b.WriteString(tsDoc(op))
		argType, optional := tsArgs(op)
		ret := "unknown"
		if op.Text || op.Streams {
			ret = "Response"
		}
		argDecl := "args: " + argType
		if optional {
			argDecl += " = {}"
		}
		fmt.Fprintf(&b, "  %s(%s, opts: CallOptions = {}): Promise<%s> {\n", tsMethod(op.Name), argDecl, ret)
		fmt.Fprintf(&b, "    return this.invoke(%q, args, opts) as Promise<%s>\n  }\n", op.Name, ret)
	}
	b.WriteString("}\n")
	return b.String()
}

// TSMethod is the plugin's method name for an operation: task_get is
// taskGet. Exported for the parity document, which names it.
func TSMethod(op string) string { return tsMethod(op) }

func tsMethod(name string) string {
	parts := strings.Split(name, "_")
	for i := 1; i < len(parts); i++ {
		if parts[i] != "" {
			parts[i] = strings.ToUpper(parts[i][:1]) + parts[i][1:]
		}
	}
	return strings.Join(parts, "")
}

func tsDoc(op Op) string {
	var b strings.Builder
	b.WriteString("  /**\n")
	fmt.Fprintf(&b, "   * %s. `%s %s`.\n", op.Summary, op.Method, op.Path)
	var notes []string
	if op.Admin {
		notes = append(notes, "Privileged: it changes the daemon rather than reading it.")
	}
	if op.Destructive {
		notes = append(notes, "Destructive: it cannot be undone, and other callers are affected.")
	}
	if op.Streams {
		notes = append(notes, "A stream: read the response body until you are done with it.")
	}
	for _, n := range notes {
		fmt.Fprintf(&b, "   * %s\n", n)
	}
	b.WriteString("   */\n")
	return b.String()
}

// tsArgs is the argument object's type, and whether it may be omitted.
func tsArgs(op Op) (string, bool) {
	if len(op.Params) == 0 {
		return "Record<string, never>", true
	}
	optional := true
	var fields []string
	for _, p := range op.Params {
		q := "?"
		if p.Required {
			q = ""
			optional = false
		}
		fields = append(fields, fmt.Sprintf("%s%s: %s", p.Name, q, tsType(p)))
	}
	return "{ " + strings.Join(fields, "; ") + " }", optional
}

func tsType(p Param) string {
	if p.Raw {
		return "BodyInit"
	}
	if len(p.Enum) > 0 {
		quoted := make([]string, len(p.Enum))
		for i, e := range p.Enum {
			quoted[i] = fmt.Sprintf("%q", e)
		}
		return strings.Join(quoted, " | ")
	}
	switch p.Type {
	case "integer", "number":
		return "number"
	case "boolean":
		return "boolean"
	case "object":
		return "Record<string, unknown>"
	case "array":
		return "unknown[]"
	}
	return "string"
}
