# ============================================================== START OF AUTOMATICALLY GENERATED CODE ==============================================================
# NOTE: THIS FILE AUTOMATICALLY GENERATED BY 'setup-bash-for-user.sh'.
# DO NOT CHANGE ANYTHING ABOVE LINE STARTING WITH: '# ============================================================== END OF AUTOMATICALLY GENERATED CODE =============================================================='
# ============================================================== START OF SYSTEM-WIDE GENERATED CODE ==============================================================

# System-wide content for .bash_profile can be added below here:
alias c='nix-shell --command "code-insiders ."'
alias cn='code-insiders .'
alias l='nix-shell --command "cargo leptos watch"'
alias n='nix-shell'
alias vim='nvim'
alias z='nix-shell --command "$(fc -ln -1)"'

# already auto handled dont touch: locate plocate
# ls exa
# find fd
# grep ripgrep
# alias ls='exa'              # exa replaces ls
# alias cat='bat'             # bat replaces cat
# alias grep='ripgrep'        # ripgrep replaces grep
# alias top='htop'            # htop replaces top
# alias rm='rmtrash'          # rmtrash replaces rm (safer delete)
# alias find='fd'             # fd replaces find (not listed but similar to ripgrep)
# alias du='ncdu'             # ncdu replaces du (not listed but more advanced version)
# alias ps='procs'            # procs replaces ps
# alias git-delta='delta'     # delta can be used as a more advanced git diff
# alias ls='exa'              # exa replaces ls
# alias cat='bat'             # bat replaces cat
# alias grep='ripgrep'        # ripgrep replaces grep
# alias top='htop'            # htop replaces top
# alias rm='rmtrash'          # rmtrash replaces rm (safer delete)
# alias find='fd'             # fd replaces find (not listed but similar to ripgrep)
# alias du='ncdu'             # ncdu replaces du (not listed but more advanced version)
# alias ps='procs'            # procs replaces ps
# alias git-delta='delta'     # delta can be used as a more advanced git diff

# alias to nix-shell the absolute path of code git repo root
# alias to dot source the absolute path of export lib in the code git repo root
# rewrite export lib to work anywhere even out of repo root

STARSHIP_PATH="$(which starship)" # do not use realpath
eval "$($STARSHIP_PATH init bash)"
# ============================================================== END OF SYSTEM-WIDE GENERATED CODE ==============================================================
# THIS FILE AUTOMATICALLY GENERATED BY 'setup-bash-for-user.sh'.
# DO NOT CHANGE ANYTHING ABOVE LINE STARTING WITH: '# ============================================================== END OF AUTOMATICALLY GENERATED CODE =============================================================='
# ============================================================== START OF PER-USER GENERATED CODE ==============================================================

# Per user content for .bash_profile can be added below here:

# ============================================================== END OF PER-USER GENERATED CODE ==============================================================
# NOTE: Only make manual changes after the following line containing the END banner:
# ============================================================== END OF AUTOMATICALLY GENERATED CODE ==============================================================
