# ============================================================== START OF AUTOMATICALLY GENERATED CODE ==============================================================
# NOTE: THIS FILE AUTOMATICALLY GENERATED BY 'setup-bash-for-user.sh'.
# DO NOT CHANGE ANYTHING ABOVE LINE STARTING WITH: '# ============================================================== END OF AUTOMATICALLY GENERATED CODE =============================================================='
# ============================================================== START OF SYSTEM-WIDE GENERATED CODE ==============================================================

# System-wide content for .bashrc can be added below here:
[[ -f ~/.bash_profile ]] && . ~/.bash_profile

# ============================================================== END OF SYSTEM-WIDE GENERATED CODE ==============================================================
# THIS FILE AUTOMATICALLY GENERATED BY 'setup-bash-for-user.sh'.
# DO NOT CHANGE ANYTHING ABOVE LINE STARTING WITH: '# ============================================================== END OF AUTOMATICALLY GENERATED CODE =============================================================='
# ============================================================== START OF PER-USER GENERATED CODE ==============================================================

# Per user content for .bashrc can be added below here:

# ============================================================== END OF PER-USER GENERATED CODE ==============================================================
# NOTE: Only make manual changes after the following line containing the END banner:
# ============================================================== END OF AUTOMATICALLY GENERATED CODE ==============================================================
