policies:
  - spec:
      conventional:
        scopes:
          - build
          - unmanaged
          - nixos
          - buck
          - repo
          - laptop-framework
          - nix
          - rust
          - nvim
          - vim
          - vi
        types:
          - build
          - chore
          - ci
          - docs
          - feat
          - fix
          - perf
          - refactor
          - style
          - test
          - bug
          - fix
          - bugfix
          - todo
          - minor
      header:
        length: 89
    type: commit
