builds:
  - id: "graph"
    dir: "src/graph"
    hooks:
      pre:
        - go mod tidy
        - go generate ./...
    binary: "graph"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - 386
      - arm64
      - arm

archives:
  - id: "graph"
    builds:
      - "graph"
    format: tar.gz
    name_template: "{{ .Binary }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

changelog:
  sort: asc
