changelog:
  sort: asc
builds:
  - id: "graph"
    dir: "sources/graph"
    hooks:
      pre:
        - cmd: go mod tidy
          dir: sources/graph
        - cmd: go generate ./...
          dir: sources/graph

    binary: "graph"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
      - android
      - js
      - wasip1
    goarch:
      # - wasm # import sys not support wasm
      - amd64
      - 386
      - arm64
      - arm
    goarm:
      - 5
      - 6
      - 7
    goamd64:
      - v1
      - v2
      - v3
      - v4
    ignore:
      - goos: linux
        goarch: wasm

      - goos: windows
        goarch: wasm

      - goos: darwin
        goarch: wasm
      - goos: darwin
        goarch: 386
      - goos: darwin
        goarch: arm

      - goos: android
        goarch: wasm
      - goos: android
        goarch: 386
      - goos: android
        goarch: arm

      - goos: js
        goarch: amd64
      - goos: js
        goarch: 386
      - goos: js
        goarch: arm64
      - goos: js
        goarch: arm

      - goos: wasip1
        goarch: amd64
      - goos: wasip1
        goarch: 386
      - goos: wasip1
        goarch: arm64
      - goos: wasip1
        goarch: arm
archives:
  - id: "graph"
    builds:
      - "graph"
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version}}_{{ .Binary }}_{{ .Os }}_{{ .Arch }}{{ .Arm }}{{ .Mips }}{{ .Amd64 }}_{{ .CommitDate }}_{{ .ShortCommit }}_{{ .Date }}"
    format_overrides:
      - goos: windows
        format: zip
