changelog:
  sort: asc
builds:
  - id: "graph"
    dir: "sources/graph"
    hooks:
      pre:
        - cmd: go mod tidy -compat=1.17
          dir: sources/graph
        # - cmd: go generate ./...
        #   dir: sources/graph
    binary: "graph"
    targets:
      - android_arm64
      - darwin_amd64_v1
      - darwin_amd64_v3
      - darwin_arm64
      # - js_wasm # sys
      - linux_386
      - linux_amd64_v1
      - linux_amd64_v3
      - linux_amd64_v4
      - linux_arm_7
      - linux_arm64
      # - wasip1_wasm # sys
      - windows_386
      - windows_amd64_v1
      - windows_amd64_v3
      - windows_amd64_v4
      - windows_arm64
archives:
  - id: "archives"
    builds:
      - "graph"
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version}}_{{ .Binary }}_{{ .Os }}_{{ .Arch }}{{ .Arm }}{{ .Mips }}{{ .Amd64 }}_{{ .ShortCommit }}_{{ .CommitDate }}_{{ .Date }}"
    format_overrides:
      - goos: windows
        format: zip
