builds:
  - id: "graph"
    dir: "sources/graph"
    hooks:
      pre:
        - cmd: go mod tidy
          dir: sources/graph
        - cmd: go generate ./...
          dir: sources/graph

    binary: "graph"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
      # - android # requires cgo
      - js
      - wasip1
    goarch:
      - wasm
      - amd64
      - 386
      - arm64
      - arm
    ignore:
      - goos: linux
        goarch: wasm

      - goos: windows
        goarch: wasm

      - goos: darwin
        goarch: wasm
      - goos: darwin
        goarch: 386
      - goos: darwin
        goarch: arm

      - goos: android
        goarch: wasm

      - goos: js
        goarch: amd64
      - goos: js
        goarch: 386
      - goos: js
        goarch: arm64
      - goos: js
        goarch: arm

      - goos: wasip1
        goarch: amd64
      - goos: wasip1
        goarch: 386
      - goos: wasip1
        goarch: arm64
      - goos: wasip1
        goarch: arm
archives:
  - id: "graph"
    builds:
      - "graph"
    format: tar.gz
    name_template: "{{ .Binary }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

changelog:
  sort: asc
# TODO: goarm goamd64 go386 etc.
