version: '3'
services:
    xen-orchestra:
        restart: always
        image: ronivay/xen-orchestra:latest
        container_name: xen-orchestra
        stop_grace_period: 1m
        ports:
            - "1337:80"
        environment:
            - HTTP_PORT=80
        cap_add:
          - SYS_ADMIN
          - DAC_READ_SEARCH
        security_opt:
          - apparmor:unconfined
        volumes:
          - xo-data:/var/lib/xo-server
          - redis-data:/var/lib/redis
        logging: &default_logging
            driver: "json-file"
            options:
                max-size: "1M"
                max-file: "2"
volumes:
  xo-data:
  redis-data:
