[formatter]

[formatter.nix]
command = "alejandra"
includes = ["*.nix"]

[formatter.prettier]
command = "prettier"
includes = [
  "*.css",
  "*.html",
  "*.js",
  "*.json",
  "*.jsx",
  "*.md",
  "*.mdx",
  "*.scss",
  "*.ts",
  "*.yaml",
  "*.toml"
]
options = ["--plugin", "prettier-plugin-toml", "--write"]

[formatter.shfmt]
command = "shfmt"
includes = ["*.sh"]
options = ["-i", "2", "-s", "-w"]

[formatter.rustfmt]
command = "rustfmt"
includes = ["*.rs"]

[formatter.shellcheck]
command = "shellcheck"
includes = ["*.sh"]
