{
  lib,
  buildNpmPackage,
  fetchurl,
  nodejs,
  ripgrep,
}:

# Desktop Commander MCP, packaged for its Remote Device.
#   https://desktopcommander.app
#   https://github.com/wonderwhy-er/DesktopCommanderMCP   (MIT, ~7.8k stars)
#
# WHY THIS PACKAGE EXISTS:
#   This is the local half of OpenAI's "Remote Desktop Commander" plugin
#   (https://openai.com/business/plugins/remote-desktop-commander). The hosted
#   Remote MCP at mcp.desktopcommander.app relays tool calls to a small device
#   agent running on your machine, and `desktop-commander remote` IS that agent.
#   The ChatGPT/Codex side of the plugin is installed from the plugin directory
#   in the app and cannot be expressed in Nix; what Nix can pin reproducibly is
#   the agent, which a systemd user unit then keeps online.
#
# Packaging notes:
#   * Not in nixpkgs (verified: no attr, no packaging PR).
#   * npm is the only distribution channel; upstream attaches no release
#     binaries, so the registry tarball is the artifact.
#   * NOT self-contained, unlike ../vercel-cli and ../pi-coding-agent. dist/ is
#     plain `tsc` output rather than a bundle: it statically imports exceljs,
#     pizzip, @modelcontextprotocol/sdk, highlight.js, markdown-it and more.
#     `node dist/index.js` against a bare tarball dies on ERR_MODULE_NOT_FOUND,
#     so buildNpmPackage with a vendored lockfile is required. Same shape as
#     ../command-code.
#   * The npm tarball ships no package-lock.json, so one is vendored here. It
#     was generated by deleting devDependencies/scripts from the published
#     package.json and running
#       npm install --package-lock-only --omit=dev --ignore-scripts
#     postPatch reapplies the same strip, so the lock keeps matching the
#     package.json that `npm ci` will see.
#   * dist/ is prebuilt upstream (`prepare` runs `tsc`), so there is no build
#     step: dontNpmBuild = true.
#   * `--ignore-scripts` is load-bearing, not tidiness: the postinstall fires a
#     telemetry ping and would run @vscode/ripgrep's downloader. Neither may
#     happen in a sandboxed build. The rg and libvips binaries still arrive
#     anyway, because upstream splits them into optional platform packages
#     (@vscode/ripgrep-linux-x64, @img/sharp-linux-x64) that need no script;
#     nixpkgs' ripgrep is additionally put on PATH as the resolver's documented
#     fallback (dist/utils/ripgrep-resolver.js strategy 2).
#   * The one real casualty of ignore-scripts is md-to-pdf: its puppeteer
#     dependency would download Chromium, so markdown-to-PDF fails until a
#     browser is configured. That path is a lazy `await import(...)` inside
#     try/catch (dist/tools/pdf/markdown.js) and does not affect the Remote
#     Device itself.
#   * Upstream exposes three bins: `desktop-commander`, plus `setup` and
#     `remove` that rewrite Claude Desktop's config and are far too generic to
#     put on PATH. Only `desktop-commander` is kept -- `desktop-commander
#     setup` still works as a subcommand of the main binary.
#   * To update: bump version, refresh `hash`,
#       nix store prefetch-file --json \
#         https://registry.npmjs.org/@wonderwhy-er/desktop-commander/-/desktop-commander-<ver>.tgz
#     regenerate package-lock.json as described above, then set npmDepsHash
#     from the build failure message.

let
  version = "0.2.52";
in
buildNpmPackage {
  pname = "desktop-commander";
  inherit version nodejs;

  src = fetchurl {
    url = "https://registry.npmjs.org/@wonderwhy-er/desktop-commander/-/desktop-commander-${version}.tgz";
    hash = "sha256-nNn1Ine0VgLVVE3f7eDwxfZFMTElYBC48qu6NXYEDGw=";
  };

  postPatch = ''
    cp ${./package-lock.json} package-lock.json
    chmod +w package.json package-lock.json

    ${lib.getExe nodejs} -e '
      const fs = require("fs");
      const p = JSON.parse(fs.readFileSync("package.json", "utf8"));
      delete p.devDependencies;
      delete p.scripts;
      delete p.workspaces;
      fs.writeFileSync("package.json", JSON.stringify(p, null, 2));
    '
  '';

  npmDepsHash = "sha256-kByqQKJxQ2pjH/20mRnD+BINQbyoXCq2PCo7gQQV49I=";

  npmFlags = [
    "--ignore-scripts"
    "--no-audit"
    "--no-fund"
  ];

  dontNpmBuild = true;

  postInstall = ''
    rm -f "$out/bin/setup" "$out/bin/remove"

    wrapProgram "$out/bin/desktop-commander" \
      --prefix PATH : ${lib.makeBinPath [ ripgrep ]}
  '';

  meta = {
    description = "MCP server (and Remote Device) that gives an AI client terminal and filesystem access";
    homepage = "https://desktopcommander.app";
    license = lib.licenses.mit;
    mainProgram = "desktop-commander";
    platforms = lib.platforms.all;
  };
}
