-- +goose Up
ALTER TABLE nodes
ADD COLUMN IF NOT EXISTS hash TEXT,
ADD COLUMN IF NOT EXISTS hashes JSON,
ADD COLUMN IF NOT EXISTS hash_ids JSON,
ADD COLUMN IF NOT EXISTS group_id UUID REFERENCES nodes(id),
ADD COLUMN IF NOT EXISTS group_ids UUID[],
ADD COLUMN IF NOT EXISTS teams JSON,
ADD COLUMN IF NOT EXISTS team_id UUID,
ADD COLUMN IF NOT EXISTS team_ids UUID[],
ADD COLUMN IF NOT EXISTS groups JSON;

-- +goose Down
ALTER TABLE nodes
DROP COLUMN IF EXISTS hash,
DROP COLUMN IF EXISTS hashes,
DROP COLUMN IF EXISTS hash_ids,
DROP COLUMN IF EXISTS group_id,
DROP COLUMN IF EXISTS group_ids,
DROP COLUMN IF EXISTS teams,
DROP COLUMN IF EXISTS team_id,
DROP COLUMN IF EXISTS team_ids,
DROP COLUMN IF EXISTS groups;
