apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: testing-privileged
spec:
  gatewayClassName: apisix
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: All
