apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: argocd-route
  namespace: testing-privileged
spec:
  parentRefs:
    - name: argocd-gateway
      namespace: testing-privileged
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /argo
        - path:
            type: PathPrefix
            value: /argo/
      backendRefs:
        - name: argocd-server
          kind: Service
          port: 80
