apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: argocd-route
spec:
  parentRefs:
    - name: argocd-gateway
      sectionName: http
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /argo
      backendRefs:
        - name: argocd-server
          port: 80
          kind: Service
          weight: 1
