apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: testing-privileged

resources:
  - gateway.yaml
  - httproute.yaml

commonLabels:
  app.kubernetes.io/name: argocd-gateway
  app.kubernetes.io/part-of: argocd

patches:
  - patch: |
      apiVersion: v1
      kind: Service
      metadata:
        name: argocd-server
      spec:
        type: ClusterIP
    target:
      kind: Service
