CREATE TABLE graph (
    id SERIAL PRIMARY KEY,
    graph_id INT REFERENCES graph(id),
    kind JSONB,
    scope JSONB,
    alias JSONB,
    content JSONB,
    arguments JSONB,
    properties JSONB,
    acl JSONB,
    public JSONB,
    unlisted JSONB,
    personal JSONB,
    owners JSONB,
    admins JSONB,
    note JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    created_by JSONB,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_by JSONB
);
CREATE TABLE nodes (
    id SERIAL PRIMARY KEY,
    graph_id INT REFERENCES graph(id),
    nodes_id INT REFERENCES nodes(id),
    kind JSONB,
    scope JSONB,
    alias JSONB,
    content JSONB,
    arguments JSONB,
    properties JSONB,
    acl JSONB,
    public JSONB,
    unlisted JSONB,
    personal JSONB,
    owners JSONB,
    admins JSONB,
    note JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    created_by JSONB,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_by JSONB
);
CREATE TABLE identifiers (
    id SERIAL PRIMARY KEY,
    graph_id INT REFERENCES graph(id),
    identifiers_id INT REFERENCES identifiers(id),
    kind JSONB,
    scope JSONB,
    alias JSONB,
    content JSONB,
    arguments JSONB,
    properties JSONB,
    acl JSONB,
    public JSONB,
    unlisted JSONB,
    personal JSONB,
    owners JSONB,
    admins JSONB,
    note JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    created_by JSONB,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_by JSONB
);
CREATE TABLE nodes_identifiers (
    id SERIAL PRIMARY KEY,
    graph_id INT REFERENCES graph(id),
    nodes_identifiers_id INT REFERENCES nodes_identifiers(id),
    kind JSONB,
    scope JSONB,
    alias JSONB,
    content JSONB,
    arguments JSONB,
    properties JSONB,
    acl JSONB,
    public JSONB,
    unlisted JSONB,
    personal JSONB,
    owners JSONB,
    admins JSONB,
    note JSONB,
    identifier_id INT REFERENCES identifiers(id),
    node_id INT NULL REFERENCES nodes(id),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    created_by JSONB,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_by JSONB
);
CREATE TABLE links (
    id SERIAL PRIMARY KEY,
    graph_id INT REFERENCES graph(id),
    links_id INT REFERENCES links(id),
    kind JSONB,
    scope JSONB,
    alias JSONB,
    content JSONB,
    arguments JSONB,
    properties JSONB,
    acl JSONB,
    public JSONB,
    unlisted JSONB,
    personal JSONB,
    owners JSONB,
    admins JSONB,
    note JSONB,
    element_identifier_id INT REFERENCES identifiers(id),
    partner_identifier_id INT REFERENCES identifiers(id),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    created_by JSONB,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_by JSONB
);
CREATE TABLE links_identifiers (
    id SERIAL PRIMARY KEY,
    graph_id INT REFERENCES graph(id),
    links_identifiers_id INT REFERENCES links_identifiers(id),
    kind JSONB,
    scope JSONB,
    alias JSONB,
    content JSONB,
    arguments JSONB,
    properties JSONB,
    acl JSONB,
    public JSONB,
    unlisted JSONB,
    personal JSONB,
    owners JSONB,
    admins JSONB,
    note JSONB,
    identifier_id INT REFERENCES identifiers(id),
    link_id INT NULL REFERENCES links(id),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    created_by JSONB,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_by JSONB
);
