apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: testing
helmCharts:
  - name: apisix
    repo: https://charts.apiseven.com
    version: 1.x.x
    releaseName: apisix
    includeCRDs: true
    valuesInline:
      dashboard:
        enabled: true
      ingress-controller:
        enabled: true
        config:
          apisix:
            serviceNamespace: testing
      global:
        namespace: testing
