apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: piraeus-datastore-external-01b
resources:
  - immediate-delete.yaml
  - immediate-retain.yaml
  - wait-delete.yaml
  - wait-retain.yaml
