# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: &namespace testing-privileged

resources:
  - https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.0.0/standard-install.yaml
  - gatewayclass.yaml

helmCharts:
  - name: apisix
    repo: https://charts.apiseven.com
    version: 2.x.x
    releaseName: apisix
    namespace: *namespace
    includeCRDs: true
    valuesInline:
      dashboard:
        enabled: true
      gateway:
        type: LoadBalancer
        annotations:
          metallb.universe.tf/address-pool: first-pool
        externalTrafficPolicy: Local
      ingress-controller:
        enabled: true
        config:
          ingressPublishService: testing-privileged/apisix-gateway
          gateway:
            enabled: true
            gatewayAPIVersion: v1beta1
          kubernetes:
            enableGatewayAPI: true
          apisix:
            serviceNamespace: *namespace
      global:
        namespace: *namespace

patches:
  - patch: |
      apiVersion: v1
      kind: Service
      metadata:
        name: apisix-gateway
        namespace: testing-privileged
      spec:
        type: LoadBalancer
    target:
      kind: Service
      name: apisix-gateway
  # https://github.com/argoproj-labs/argocd-autopilot/issues/631
  # https://github.com/apache/apisix-helm-chart/issues/531
  # https://github.com/apache/apisix-helm-chart/pull/797
  # ignoreDifferences:
  #   - group: apiextensions.k8s.io
  #     kind: CustomResourceDefinition
  #     jqPathExpressions:
  #       - '.spec.versions[].additionalPrinterColumns[]'
