apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: testing-privileged
helmCharts:
  - name: apisix
    repo: https://charts.apiseven.com
    version: 2.x.x
    releaseName: apisix
    namespace: testing-privileged
    includeCRDs: true
    valuesInline:
      dashboard:
        enabled: true
      ingress-controller:
        enabled: true
        config:
          apisix:
            serviceNamespace: testing-privileged
      global:
        namespace: testing-privileged

  # https://github.com/argoproj-labs/argocd-autopilot/issues/631
  # https://github.com/apache/apisix-helm-chart/issues/531
  # https://github.com/apache/apisix-helm-chart/pull/797
  # ignoreDifferences:
  #   - group: apiextensions.k8s.io
  #     kind: CustomResourceDefinition
  #     jqPathExpressions:
  #       - '.spec.versions[].additionalPrinterColumns[]'
