apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: testing-privileged
helmCharts:
  - name: apisix
    repo: https://charts.apiseven.com
    version: 2.x.x
    releaseName: apisix
    namespace: testing-privileged
    includeCRDs: true
    valuesInline:
      dashboard:
        enabled: true
      ingress-controller:
        enabled: true
        config:
          apisix:
            serviceNamespace: testing-privileged
      global:
        namespace: testing-privileged
patches:
  - path: ignore-additional-printer-columns-patch.yaml
