package conformance

// Transports: stdio, HTTP+SSE, Streamable HTTP.
func init() {
	register(
		C("stdio-message-may-be-batch", "mcpclient.TestReceivedBatchesAreSplit/2025-03-26/messages/client-accepts-batched-server-messages"),
		C("http-sse-client-post-to-endpoint", "mcpclient.TestHTTPSSETransport/2024-11-05/transport-http-sse/client-posts-to-endpoint-and-reads-stream"),
		C("http-sse-client-backcompat-probe-400-404-405", "mcpclient.TestHTTPSSETransport/2025-11-25/transport-http-sse/backcompat-probe-refusal-is-recognised", "pool.TestHTTPSSEFallback/2025-11-25/transport-http-sse/client-falls-back-to-get-endpoint-and-caches-it"),
		C("http-sse-client-backcompat-probe-any-4xx", "pool.TestHTTPSSEFallback/2025-11-25/transport-http-sse/client-falls-back-to-get-endpoint-and-caches-it@2025-03-26,2025-06-18"),
		C("http-sse-client-backcompat-probe-non-modern-body", "mcpclient.TestHTTPEraProbe/2026-07-28/http-compat/legacy-refused-too-is-typed-for-http-sse"),
		C("streamable-http-client-sends-metadata-headers", "mcpclient.TestModernHTTPHeaders/2026-07-28/transport/client-sends-standard-and-param-headers"),
		C("streamable-http-standard-headers-required", "mcpclient.TestTheVersionHeaderFollowsTheFrame/2026-07-28/transport/standard-headers-mcp-method-and-mcp-name"),
		C("streamable-http-mcp-name-base64", "mcpclient.TestHeaderValueEncoding/2026-07-28/transport/value-encoding-examples"),
		C("streamable-http-param-value-encoding", "mcpclient.TestHeaderValueEncoding/2026-07-28/transport/value-encoding-examples"),
		C("streamable-http-client-header-construction", "mcpclient.TestParamHeaders/2026-07-28/transport/param-headers-mirror-and-omit-null"),
		C("streamable-http-x-mcp-header-client-must-mirror", "mcpclient.TestParamHeaders/2026-07-28/transport/param-headers-mirror-and-omit-null"),
		C("streamable-http-client-rejects-invalid-x-mcp-header", "mcpclient.TestToolHeaderAnnotations/2026-07-28/transport/client-rejects-invalid-x-mcp-header", "mcpclient.TestModernHTTPHeaders/2026-07-28/transport/client-excludes-tool-with-invalid-x-mcp-header"),
		C("streamable-http-client-relist-on-header-mismatch", "mcpclient.TestModernHTTPHeaders/2026-07-28/transport/client-relists-and-retries-on-header-mismatch"),
		C("streamable-http-client-polls-after-close", "mcpclient.TestLegacyHTTPStreamResumption/2025-11-25/transport/client-resumes-closed-stream-with-last-event-id-after-retry"),
		C("streamable-http-client-respects-retry", "mcpclient.TestLegacyHTTPStreamResumption/2025-11-25/transport/client-resumes-closed-stream-with-last-event-id-after-retry"),
		C("streamable-http-client-resume-with-last-event-id", "mcpclient.TestLegacyHTTPStreamResumption/2025-11-25/transport/client-resumes-closed-stream-with-last-event-id-after-retry@2025-03-26,2025-06-18,2025-11-25"),
		C("stdio-client-correlates-subscription-id", "mcpclient.TestModernListenStream/2026-07-28/transport-stdio/client-correlates-subscription-id"),
		SReq("conformance.TestTransportServer",
			"stdio-no-embedded-newlines",
			"stdio-server-stdout-only-mcp",
			"stdio-server-may-log-to-stderr",
			"stdio-message-is-single",
			"stdio-message-may-be-batch",
			"stdio-server-exit-on-eof",
			"stdio-server-may-close-stdout",
			"stdio-server-stop-cancelled-work",
			"stdio-server-silent-after-cancel",
			"stdio-server-no-requests",
			"stdio-server-cancelled-only-for-listen",
			"streamable-http-server-single-endpoint-post-get",
			"streamable-http-server-single-endpoint-post",
			"streamable-http-server-validate-origin",
			"streamable-http-server-403-invalid-origin",
			"streamable-http-server-bind-localhost",
			"streamable-http-server-202-for-non-request",
			"streamable-http-server-error-status-if-rejected",
			"streamable-http-server-json-or-sse-for-request",
			"streamable-http-sse-includes-response",
			"streamable-http-post-sse-may-carry-requests",
			"streamable-http-sse-not-closed-before-response",
			"streamable-http-server-terminates-sse-after-response",
			"streamable-http-no-broadcast",
			"streamable-http-disconnect-not-cancel",
			"streamable-http-close-is-cancel",
			"streamable-http-stop-cancelled-work",
			"streamable-http-silent-after-cancel",
			"streamable-http-get-sse-or-405",
			"streamable-http-get-close-any-time",
			"streamable-http-server-may-assign-session",
			"streamable-http-session-id-secure",
			"streamable-http-session-id-visible-ascii",
			"streamable-http-server-404-terminated-session",
			"streamable-http-server-may-405-delete",
			"streamable-http-server-may-terminate-on-session-expiry",
			"streamable-http-server-assumes-2025-03-26",
			"streamable-http-server-400-unsupported-version-header",
			"streamable-http-missing-version-header-legacy",
			"streamable-http-header-mismatch-400-jsonrpc",
			"streamable-http-server-rejects-header-body-mismatch",
			"streamable-http-protocol-version-header-matches-meta",
			"streamable-http-server-decodes-before-compare",
			"streamable-http-server-validates-param-headers",
			"streamable-http-header-names-case-insensitive",
			"streamable-http-unknown-method-404",
			"streamable-http-unsupported-version-400",
			"streamable-http-missing-capability-400",
			"streamable-http-x-accel-buffering",
			"streamable-http-sse-comment-keepalive",
			"streamable-http-sse-notifications-must-relate",
			"streamable-http-no-resumability",
			"streamable-http-sse-no-requests",
			"http-sse-deprecated-no-new-adoption",
		),
		CReq("conformance.TestTransportClient",
			"streamable-http-get-close-any-time",
			"transport-client-should-support-stdio",
			"stdio-no-embedded-newlines",
			"stdio-client-stdin-only-mcp",
			"stdio-message-is-single",
			"stdio-client-may-capture-stderr",
			"stdio-client-stderr-not-error",
			"stdio-client-cancel-by-notification",
			"stdio-client-no-responses",
			"stdio-modern-only-client-probe",
			"stdio-no-fallback-on-modern-error",
			"stdio-client-shutdown-sequence",
			"streamable-http-client-post-every-message",
			"streamable-http-client-accept-both",
			"streamable-http-post-body-may-batch",
			"streamable-http-post-body-single",
			"streamable-http-post-body-request-or-notification",
			"http-sse-deprecated-no-new-adoption",
			"streamable-http-no-resumability",
			"streamable-http-client-echoes-session",
			"streamable-http-client-delete-session",
			"streamable-http-client-handles-session-securely",
			"streamable-http-client-supports-json-and-sse",
			"streamable-http-sse-comment-keepalive",
			"streamable-http-client-cancel-by-notification",
			"streamable-http-multiple-streams",
			"streamable-http-protocol-version-header-every-post",
			"streamable-http-protocol-version-header-matches-meta",
			"streamable-http-protocol-version-header-is-negotiated",
			"streamable-http-header-names-case-insensitive",
			"streamable-http-intermediary-http-error",
		),
	)
	registerGaps(
		Gap{ID: "streamable-http-client-reissue-broken-request", Side: Client, Issue: "#203", Why: "a broken 2026-07-28 response stream is reported lost to the caller (http.go); nothing re-issues the request with a new id"},
		Gap{ID: "streamable-http-client-reinit-on-404", Side: Client, Issue: "#203", Why: "a 404 for the session is returned as an error; no new initialize"},
		Gap{ID: "stdio-client-restart-crashed-server", Side: Client, Issue: "#257", Why: "unverified: the in-flight call fails and the pool respawns only on the next acquire, subject to its start-failure cooldown"},
	)
}
