package conformance

// Roots, sampling, elicitation.
func init() {
	// The broker and `mcpx elicit` give the person answering the choices;
	// they sit above the protocol and are the same for every revision.
	const human = "elicit.TestRoutingSendsCredentialsToAHumanAndTheRestToTheAgent@2025-06-18,2025-11-25,2026-07-28"
	const decline = "elicit.TestAnsweringAfterTheProcessDiedStillWorks@2025-06-18,2025-11-25,2026-07-28"
	const expire = "elicit.TestAnExpiredQuestionBecomesCancelNotDecline@2025-06-18,2025-11-25,2026-07-28"
	const cliAnswer = "e2e.TestElicitationsCanBeListedAndAnsweredFromTheCommandLine@2025-11-25,2026-07-28"
	register(
		C("elicitation-client-32602-on-undeclared-mode", "mcpclient.TestElicitationDeclarations/2025-11-25/elicitation/undeclared-mode-is-32602"),
		C("elicitation-client-prepopulate-defaults", "mcpclient.TestElicitationDeclarations/2025-11-25/elicitation/client-applies-schema-defaults",
			"mcpclient.TestModernElicitationAppliesSchemaDefaults/2026-07-28/elicitation/client-applies-schema-defaults"),
		C("elicitation-app-decline-cancel-options", decline, expire),
		C("elicitation-client-decline-cancel-options", decline, expire),
		C("elicitation-client-allow-decline-any-time", decline),
		C("elicitation-client-user-approval-controls", human),
		C("elicitation-client-open-url-securely", human),
		C("elicitation-client-manual-retry-cancel-controls", cliAnswer),
		SReq("conformance.TestClientFeaturesServer",
			"sampling-tool-result-message-only-tool-results",
			"sampling-tool-use-result-balance",
			"sampling-toolresult-id-must-match-tooluse",
			"sampling-toolresult-structured-conform-outputschema",
			"sampling-message-must-have-role-and-content",
			"sampling-server-answer-every-tooluse",
			"sampling-deprecated-new-impls-should-not-adopt",
			"sampling-both-iteration-limits-tool-loops",
			"elicitation-request-must-include-mode-and-message",
			"elicitation-form-request-shape",
			"elicitation-server-may-omit-mode-for-form",
			"elicitation-no-clickable-urls-in-form",
			"elicitation-server-no-sensitive-info-in-form-mode",
			"elicitation-server-no-sensitive-info",
			"elicitation-form-schema-flat-primitives",
			"elicitation-server-may-request-during-client-request",
			"elicitation-empty-capability-means-form-only",
			"elicitation-server-no-undeclared-modes",
			"elicitation-url-request-shape-with-id",
			"elicitation-url-request-shape",
			"elicitation-url-must-be-valid",
			"elicitation-url-no-sensitive-user-info",
			"elicitation-url-not-pre-authenticated",
			"elicitation-url-https-outside-dev",
			"elicitation-server-sensitive-via-url-mode",
			"elicitation-server-must-not-self-authorize-via-url",
			"elicitation-third-party-creds-not-via-client",
			"elicitation-user-authorizes-server-directly",
			"elicitation-server-not-transmit-url-creds-to-client",
			"elicitation-no-32042-in-2026",
			"elicitation-server-handle-decline-cancel-failure",
			"elicitation-server-bind-to-client-and-user",
			"elicitation-url-required-error-only-when-required",
			"elicitation-url-required-error-lists-elicitations",
			"elicitation-url-required-error-url-mode-with-id",
			"elicitation-server-may-return-url-required-error",
			"elicitation-complete-only-to-initiating-client",
			"elicitation-complete-must-carry-id",
			"elicitation-server-may-send-complete-notification",
		),
		CReq("conformance.TestClientFeaturesClient",
			"roots-client-declare-capability-at-initialize",
			"roots-client-declare-capability-per-request-meta",
			"roots-client-listchanged-must-notify",
			"roots-deprecated-new-impls-should-not-adopt",
			"roots-deprecated-existing-should-migrate",
			"roots-client-return-jsonrpc-errors",
			"sampling-client-declare-capability-at-initialize",
			"sampling-client-declare-capability-per-request-meta",
			"sampling-client-declare-tools-capability",
			"sampling-deprecated-new-impls-should-not-adopt",
			"sampling-stopreason-custom-values",
			"sampling-tooluse-meta-preserve",
			"sampling-toolresult-id-must-match-tooluse",
			"sampling-tool-result-message-only-tool-results",
			"sampling-tool-use-result-balance",
			"sampling-toolresult-structured-conform-outputschema",
			"sampling-message-must-have-role-and-content",
			"sampling-client-errors-user-rejected",
			"sampling-human-in-loop-can-deny",
			"sampling-both-iteration-limits-tool-loops",
			"elicitation-client-declare-capability-at-initialize",
			"elicitation-client-declare-capability-per-request-meta",
			"elicitation-client-support-at-least-one-mode",
			"elicitation-empty-capability-means-form-only",
			"elicitation-client-missing-mode-is-form",
			"elicitation-client-elicitationid-opaque",
			"elicitation-client-no-url-prefetch",
			"elicitation-client-no-open-without-consent",
			"elicitation-client-show-full-url",
			"elicitation-client-no-clickable-except-url-field",
			"elicitation-no-32042-in-2026",
			"elicitation-app-show-requesting-server",
			"elicitation-client-show-requesting-server",
			"elicitation-client-clear-what-and-why",
			"elicitation-client-ignore-unknown-complete",
			"elicitation-client-may-auto-retry-on-complete",
		),
	)
	registerGaps(
		Gap{ID: "sampling-app-review-ui", Side: Client, Issue: "#256", Why: "a sampling request is routed to the agent audience; nothing lets a person review or edit the prompt or the result"},
		Gap{ID: "sampling-app-view-edit-prompts", Side: Client, Issue: "#256", Why: "a sampling request is routed to the agent audience; nothing lets a person review or edit the prompt or the result"},
		Gap{ID: "sampling-app-review-responses", Side: Client, Issue: "#256", Why: "a sampling request is routed to the agent audience; nothing lets a person review or edit the prompt or the result"},
		Gap{ID: "sampling-client-user-approval-controls", Side: Client, Issue: "#256", Why: "a sampling request is routed to the agent audience; nothing lets a person review or edit the prompt or the result"},
		Gap{ID: "sampling-both-validate-message-content", Side: Client, Issue: "#256", Why: "sampling messages and results are relayed without validation"},
		Gap{ID: "sampling-both-validate-message-content", Side: Server, Issue: "#256", Why: "sampling messages and results are relayed without validation"},
		Gap{ID: "sampling-both-handle-sensitive-data", Side: Client, Issue: "#255", Why: "prompts and answers are stored unredacted in state/logs/elicit.db under a 0755 directory and published on the event bus"},
		Gap{ID: "sampling-both-handle-sensitive-data", Side: Server, Issue: "#255", Why: "prompts and answers are stored unredacted in state/logs/elicit.db under a 0755 directory and published on the event bus"},
		Gap{ID: "sampling-messages-not-retained-between-requests", Side: Client, Issue: "#255", Why: "every CreateMessageRequest is kept in state/logs/elicit.db and never pruned"},
		Gap{ID: "elicitation-state-storage-protected", Side: Server, Issue: "#255", Why: "pending questions and answers are readable by any local user (0755 directory, default file mode)"},
		Gap{ID: "sampling-client-rate-limit", Side: Client, Issue: "#257", Why: "no per-server or per-session limit on sampling requests"},
		Gap{ID: "elicitation-client-rate-limit", Side: Client, Issue: "#257", Why: "no per-server limit on elicitation requests"},
		Gap{ID: "sampling-client-error-on-tools-without-capability", Side: Client, Issue: "#210", Why: "a sampling request carrying tools is passed on though sampling.tools was not declared"},
		Gap{ID: "sampling-client-errors-user-rejected-and-tool-shape", Side: Client, Issue: "#256", Why: "every refusal or failure is -32603; neither -1 nor -32602 is produced"},
		Gap{ID: "sampling-server-no-tools-without-capability", Side: Server, Issue: "#210", Why: "an upstream sampling request is relayed as-is: tools and includeContext reach a client that did not declare sampling.tools or sampling.context"},
		Gap{ID: "sampling-server-includecontext-only-with-context-capability", Side: Server, Issue: "#210", Why: "an upstream sampling request is relayed as-is: tools and includeContext reach a client that did not declare sampling.tools or sampling.context"},
		Gap{ID: "sampling-server-avoid-includecontext-values", Side: Server, Issue: "#210", Why: "an upstream sampling request is relayed as-is: tools and includeContext reach a client that did not declare sampling.tools or sampling.context"},
		Gap{ID: "elicitation-app-review-modify-responses", Side: Client, Issue: "#255", Why: "mcpx elicit prints the raw request: no review step, no domain emphasis or punycode warning, no defaults pre-filled"},
		Gap{ID: "elicitation-client-form-review-modify-responses", Side: Client, Issue: "#255", Why: "mcpx elicit prints the raw request: no review step, no domain emphasis or punycode warning, no defaults pre-filled"},
		Gap{ID: "elicitation-client-url-show-domain-and-consent", Side: Client, Issue: "#255", Why: "mcpx elicit prints the raw request: no review step, no domain emphasis or punycode warning, no defaults pre-filled"},
		Gap{ID: "elicitation-client-handle-urls-carefully", Side: Client, Issue: "#255", Why: "mcpx elicit prints the raw request: no review step, no domain emphasis or punycode warning, no defaults pre-filled"},
		Gap{ID: "elicitation-client-highlight-domain", Side: Client, Issue: "#255", Why: "mcpx elicit prints the raw request: no review step, no domain emphasis or punycode warning, no defaults pre-filled"},
		Gap{ID: "elicitation-client-warn-punycode", Side: Client, Issue: "#255", Why: "mcpx elicit prints the raw request: no review step, no domain emphasis or punycode warning, no defaults pre-filled"},
		Gap{ID: "elicitation-client-validate-responses", Side: Client, Issue: "#255", Why: "an answer is checked only for non-empty content, not against requestedSchema"},
		Gap{ID: "elicitation-both-validate-against-schema", Side: Client, Issue: "#255", Why: "an answer is checked only for non-empty content, not against requestedSchema"},
		Gap{ID: "elicitation-both-validate-against-schema", Side: Server, Issue: "#255", Why: "an answer is checked only for non-empty content, not against requestedSchema"},
		Gap{ID: "elicitation-server-validate-received-data", Side: Server, Issue: "#255", Why: "a client answer is relayed upstream without a schema check"},
		Gap{ID: "elicitation-server-must-return-32042", Side: Server, Issue: "#214", Why: "a url question for a client that cannot take it stays with the broker; -32042 is never returned"},
		Gap{ID: "elicitation-server-state-bound-to-user", Side: Server, Issue: "#257", Why: "mcpx has no authenticated user: state is bound to the request, the session id is whatever the caller sends"},
		Gap{ID: "elicitation-server-stored-state-bound-to-user", Side: Server, Issue: "#257", Why: "mcpx has no authenticated user: state is bound to the request, the session id is whatever the caller sends"},
		Gap{ID: "elicitation-server-no-trust-client-user-id", Side: Server, Issue: "#257", Why: "mcpx has no authenticated user: state is bound to the request, the session id is whatever the caller sends"},
		Gap{ID: "elicitation-server-follow-best-practices", Side: Server, Issue: "#255", Why: "requestState signing is sound; question storage is world-readable and there is no user identity"},
		Gap{ID: "elicitation-state-not-session-id-alone", Side: Server, Issue: "#257", Why: "state is bound to the request, not a user; there is no user to bind to"},
	)
}
