package conformance

// Tools, resources, prompts.
func init() {
	// Aggregation is done by the daemon's registry, above the protocol: it is
	// the same whatever revision an upstream speaks, so these tests hold it
	// for 2026-07-28 as for every other.
	register(
		// Delivery end to end is the daemon's (#247), the same for every legacy revision.
		S("resources-subscribe-cap-meaning-legacy",
			"e2e.TestResourceSubscriptionsReachUpstream/2025-11-25/resources/stdio-subscribe-delivers-upstream-updates-under-the-mcpx-uri@2024-11-05,2025-03-26,2025-06-18,2025-11-25",
			"e2e.TestResourceSubscriptionsReachUpstream/2025-11-25/resources/http-subscribe-delivers-upstream-updates-on-the-get-stream@2025-03-26,2025-06-18,2025-11-25"),
		S("resources-subscribe-cap-meaning-2026",
			"e2e.TestResourceSubscriptionsReachUpstream/2026-07-28/subscriptions/listen-delivers-upstream-updates-and-acks-only-what-it-can"),
		S("resources-custom-scheme-rfc3986", PerRev("cli.TestMCPXResourceURIs", "resources/resources-custom-scheme-rfc3986", "2025-06-18", "2025-11-25", "2026-07-28")...),
		C("resources-subscribe-via-listen", "mcpclient.TestModernListenStream/2026-07-28/subscriptions/resource-subscription-reopens-listen"),
		C("tools-x-mcp-header-reject-excludes", "mcpclient.TestModernHTTPHeaders/2026-07-28/transport/client-excludes-tool-with-invalid-x-mcp-header"),
		C("tools-x-mcp-header-reject-log", "mcpclient.TestModernHTTPHeaders/2026-07-28/transport/client-excludes-tool-with-invalid-x-mcp-header"),
		C("tools-aggregator-disambiguate", "e2e.TestDuplicateNamespaceIsRejected@2026-07-28",
			"e2e.TestAliasExposesASubsetOfTheSameServer@2026-07-28"),
		C("tools-aggregator-not-by-servername", "e2e.TestDuplicateNamespaceIsRejected@2026-07-28"),
		SReq("conformance.TestFeaturesServer",
			"resources-sec-binary-encoded",
			"tools-declare-capability",
			"resources-declare-capability",
			"prompts-declare-capability",
			"prompts-declare-capability-discover",
			"resources-cap-features-independent",
			"tools-list-must-respond-when-declared",
			"resources-list-must-respond-when-declared",
			"prompts-list-must-respond-when-declared",
			"tools-list-may-be-empty-change",
			"tools-embedded-implies-resources-cap",
			"tools-list-not-per-connection",
			"resources-list-not-per-connection",
			"prompts-list-not-per-connection",
			"tools-list-deterministic-order",
			"tools-list-changed-notify",
			"tools-list-changed-notify-to-listeners",
			"prompts-list-changed-notify",
			"prompts-list-changed-notify-to-listeners",
			"resources-list-changed-notify",
			"tools-list-changed-means-emit",
			"tools-inputschema-type-object-root",
			"tools-inputschema-valid-not-null",
			"tools-inputschema-no-params-recommended",
			"tools-name-length",
			"tools-name-charset",
			"tools-name-no-special",
			"tools-name-unique-in-server",
			"tools-output-schema-conform",
			"tools-output-schema-object-root",
			"tools-structured-also-text",
			"tools-structured-any-json",
			"tools-structured-object-only",
			"tools-error-unknown-tool-protocol",
			"tools-result-lookup-errors-protocol",
			"tools-name-case-sensitive",
			"tools-result-iserror-for-tool-errors",
			"tools-error-input-validation-execution",
			"tools-error-invalid-args-protocol",
			"tools-embedded-resource-may",
			"tools-resource-link-may",
			"tools-resource-link-may-not-listed",
			"tools-call-input-required-may",
			"tools-call-inputrequests-declared-only",
			"resources-read-input-required-may",
			"prompts-get-input-required-may",
			"resources-not-found-32002",
			"resources-not-found-32602",
			"resources-no-empty-contents-for-missing",
			"resources-internal-32603",
			"resources-read-multiple-may",
			"resources-file-xdg-mime-may",
			"resources-https-only-if-client-fetchable",
			"resources-https-else-other-scheme",
			"resources-annotations-defs",
			"resources-sec-validate-uris",
			"prompts-image-base64-mime",
			"prompts-audio-base64-mime",
			"prompts-embedded-must-include",
			"prompts-resource-link-may",
			"prompts-errors-32602-32603",
			"prompts-validate-args",
			"prompts-validate-io",
			"prompts-respect-capability-negotiation",
		),
		CReq("conformance.TestFeaturesClient",
			"tools-client-exec-errors-to-llm",
			"tools-client-protocol-errors-to-llm-may",
			"tools-name-case-sensitive",
			"tools-resource-link-may-not-listed",
			"tools-x-mcp-header-stdio-may-ignore",
			"resources-client-accept-32002",
			"resources-subscribe-rpc",
			"resources-unsubscribe-follows-subscribe",
			"resources-updated-may-be-subresource",
			"prompts-client-paginate",
			"prompts-respect-capability-negotiation",
		),
	)
	registerGaps(
		Gap{ID: "resources-annotations-defs", Side: Client, Issue: "#207", Why: "mcpclient.Resource has no annotations field; they are dropped on parse"},
		Gap{ID: "tools-display-name-precedence", Side: Client, Issue: "#207", Why: "tool title and annotations.title are carried but nothing that displays a tool uses them"},
		Gap{ID: "tools-annotations-untrusted", Side: Client, Issue: "#257", Why: "destructiveHint from any upstream decides whether a call is confirmed; a false hint (or readOnlyHint true) is trusted"},
		Gap{ID: "tools-annotations-hints-no-decisions", Side: Client, Issue: "#257", Why: "the consumer confirmDestructive gate is decided by an untrusted upstream annotation"},
		Gap{ID: "prompts-validate-io", Side: Client, Issue: "#257", Why: "an upstream prompts/get result is passed on unvalidated"},
	)
}
