package conformance

// Cancellation, progress, pagination, logging, completion.
func init() {
	const teardown = "mcpserver.TestSubscriptionsListen/2026-07-28/subscriptions/server-teardown-sends-cancelled-then-result"
	const closeCancels = "conformance.TestTransportServer/2026-07-28/transport-streamable-http/streamable-http-close-is-cancel"
	register(
		S("cancellation-ref-client-issued-in-progress", teardown),
		S("cancellation-server-must-send-cancelled-on-listen-teardown", teardown),
		S("cancellation-server-only-for-listen", teardown,
			"conformance.TestTransportServer/2026-07-28/transport-stdio/stdio-server-cancelled-only-for-listen"),
		S("cancellation-http-disconnect-is-cancel", closeCancels),
		S("cancellation-http-no-messages-after-close", closeCancels,
			"conformance.TestTransportServer/2026-07-28/transport-streamable-http/streamable-http-silent-after-cancel"),
		SReq("conformance.TestUtilitiesServer",
			"cancellation-ref-same-direction-in-progress",
			"cancellation-requestid-required-non-task-forbidden-task",
			"cancellation-sender-ignore-late-response",
			"cancellation-task-use-tasks-cancel",
			"cancellation-timeout-then-cancel",
			"cancellation-timeouts-establish",
			"cancellation-max-timeout-despite-progress",
			"cancellation-timeouts-per-request-configurable",
			"cancellation-receiver-should-stop-free-no-response",
			"cancellation-server-should-stop-free-no-response",
			"cancellation-processing-should-cease",
			"cancellation-receiver-may-ignore",
			"cancellation-server-may-ignore",
			"cancellation-ignore-invalid",
			"cancellation-handle-races",
			"progress-must-increase",
			"progress-message-human-readable",
			"progress-only-active-tokens",
			"progress-rate-limit",
			"progress-stop-after-completion",
			"progress-receiver-may-skip",
			"progress-server-may-skip",
			"progress-task-token-lives-with-task",
			"progress-task-same-token",
			"progress-task-stop-at-terminal",
			"progress-http-notifications-relate-to-request",
			"progress-token-unique-sender",
			"pagination-stable-cursors",
			"pagination-invalid-cursor-graceful",
			"pagination-invalid-cursor-32602",
			"logging-declare-capability",
			"logging-setlevel-at-or-above",
			"logging-unset-server-chooses",
			"logging-server-hygiene",
			"logging-no-secrets-pii",
			"logging-impl-validate-control",
			"logging-deprecated",
			"logging-no-message-without-loglevel",
			"logging-request-scoped-only",
			"logging-errors-setlevel",
			"logging-invalid-loglevel-reject-request",
			"completion-declare-capability",
			"completion-max-100",
			"completion-errors",
		),
		CReq("conformance.TestUtilitiesClient",
			"cancellation-client-should-send",
			"cancellation-stdio-client-must-send",
			"cancellation-timeout-then-cancel",
			"cancellation-timeouts-establish",
			"cancellation-max-timeout-despite-progress",
			"cancellation-ref-same-direction-in-progress",
			"cancellation-ref-client-issued-in-progress",
			"cancellation-requestid-required-non-task-forbidden-task",
			"cancellation-sender-ignore-late-response",
			"cancellation-client-ignore-late-response",
			"cancellation-task-use-tasks-cancel",
			"cancellation-timeouts-per-request-configurable",
			"cancellation-client-must-not-cancel-initialize",
			"cancellation-receiver-should-stop-free-no-response",
			"cancellation-processing-should-cease",
			"cancellation-receiver-may-ignore",
			"cancellation-ignore-invalid",
			"cancellation-handle-races",
			"cancellation-log-reasons",
			"progress-token-string-or-int",
			"progress-token-unique-sender",
			"progress-token-unique-client",
			"progress-receiver-may-skip",
			"progress-track-tokens",
			"progress-rate-limit",
			"pagination-cursor-opaque",
			"pagination-missing-nextcursor-end",
			"pagination-no-fixed-page-size",
			"pagination-no-persist-across-sessions",
			"pagination-support-both-flows",
			"pagination-empty-cursor-not-end",
			"logging-client-may-setlevel",
			"logging-impl-validate-control",
			"logging-no-secrets-pii",
			"completion-context-arguments",
			"completion-client-should",
		),
	)
	registerGaps(
		Gap{ID: "cancellation-log-reasons", Side: Server, Issue: "#77", Why: "a cancellation reason reaches Server.OnCancel, which nothing outside tests sets; it is never logged"},
		Gap{ID: "completion-security", Side: Server, Issue: "#213", Why: "completion/complete has no rate limit and no per-caller access control"},
		Gap{ID: "completion-server-should", Side: Server, Issue: "#213", Why: "values are sorted alphabetically and matched by substring, not ranked by relevance; no rate limit"},
	)
}
