package conformance

// Tasks, caching, subscriptions, MRTR.
func init() {
	register(
		C("subscriptions-list-changed-via-listen", "mcpclient.TestModernListenStream/2026-07-28/subscriptions/client-opens-listen-for-declared-capabilities"),
		C("subscriptions-client-check-ack", "mcpclient.TestModernListenStream/2026-07-28/subscriptions/client-checks-acknowledged-subset"),
		C("subscriptions-stdio-client-correlate", "mcpclient.TestModernListenStream/2026-07-28/transport-stdio/client-correlates-subscription-id"),
		S("ext-tasks-server-advertise-discover", "mcpserver.TestCapabilitiesPerRevision/2026-07-28/capabilities/tasks-only-as-extension"),
		S("ext-tasks-never-unsolicited", "mcpserver.TestTasksPerEra/2026-07-28/tasks/no-task-without-the-extension-task-param-ignored"),
		S("ext-tasks-server-decides", "mcpserver.TestTasksPerEra/2026-07-28/tasks/server-directed-CreateTaskResult-is-flat", "mcpserver.TestTasksPerEra/2026-07-28/tasks/fast-call-is-answered-directly", "mcpserver.TestATaskSupportingToolBecomesATaskWithoutWaitingTaskAfter@2026-07-28", "mcpserver.TestAQuestionAskedUpFrontIsAnsweredBeforeTheTaskExists@2026-07-28"),
		S("ext-tasks-createtaskresult-shape", "mcpserver.TestTasksPerEra/2026-07-28/tasks/server-directed-CreateTaskResult-is-flat"),
		S("ext-tasks-get-carries-result", "mcpserver.TestTasksPerEra/2026-07-28/tasks/server-directed-CreateTaskResult-is-flat", "mcpserver.TestTasksPerEra/2026-07-28/tasks/tool-isError-is-completed-not-failed"),
		S("ext-tasks-update", "mcpserver.TestTasksPerEra/2026-07-28/tasks/update-and-cancel-ack-empty-unknown-is-32602", "mcpserver.TestATaskAskingAQuestionIsInputRequiredAndTasksUpdateAnswersIt@2026-07-28"),
		S("ext-tasks-notifications-via-listen", "mcpserver.TestSubscriptionsListen/2026-07-28/subscriptions/taskIds-without-the-extension-is-32021", "mcpserver.TestListenDeliversTaskStatusNotifications@2026-07-28", "mcpserver.TestListenReportsATaskThatAlreadyFinished@2026-07-28"),
		S("tasks-unidentified-no-list", "mcpserver.TestTasksPerEra/2025-11-25/tasks/another-connection-cannot-list-or-read-it"),
		S("caching-server-must-hint", "mcpserver.TestModernEnvelope/2026-07-28/caching/tools-list-has-ttlMs-and-cacheScope", "mcpserver.TestModernEnvelope/2026-07-28/caching/resources-read-has-ttlMs-and-cacheScope", "mcpserver.TestModernEnvelope/2026-07-28/caching/server-discover-has-ttlMs-and-cacheScope"),
		S("cache-ttl-scope-required",
			"mcpserver.TestModernEnvelope/2026-07-28/caching/server-discover-has-ttlMs-and-cacheScope",
			"mcpserver.TestModernEnvelope/2026-07-28/caching/tools-list-has-ttlMs-and-cacheScope",
			"mcpserver.TestModernEnvelope/2026-07-28/caching/prompts-list-has-ttlMs-and-cacheScope",
			"mcpserver.TestModernEnvelope/2026-07-28/caching/resources-templates-list-has-ttlMs-and-cacheScope",
			"mcpserver.TestModernEnvelope/2026-07-28/caching/resources-list-has-ttlMs-and-cacheScope",
			"mcpserver.TestModernEnvelope/2026-07-28/caching/resources-read-has-ttlMs-and-cacheScope"),
		S("caching-input-required-no-hints", "mcpserver.TestMRTRServerRules/2026-07-28/mrtr/requestState-is-bound-to-the-originating-request"),
		S("caching-page-same-scope", "mcpserver.TestModernEnvelope/2026-07-28/caching/every-page-has-the-same-cacheScope"),
		S("mrtr-requeststate-attacker-controlled", "mcpserver.TestMRTRServerRules/2026-07-28/mrtr/tampered-requestState-is-rejected"),
		S("mrtr-requeststate-replay-fields", "mcpserver.TestMRTRServerRules/2026-07-28/mrtr/requestState-is-bound-to-the-originating-request"),
		S("mrtr-server-reask-missing-rather-than-error", "mcpserver.TestMRTRServerRules/2026-07-28/mrtr/missing-input-response-asks-again"),
		S("mrtr-no-assume-retry", "mcpserver.TestMRTRServerRules/2026-07-28/mrtr/missing-input-response-asks-again"),
		S("mrtr-server-requests-via-mrtr", "mcpserver.TestElicitationPerEra/2026-07-28/elicitation/inputRequests-carry-no-elicitationId"),
		S("subscriptions-ack-first-with-id", "mcpserver.TestSubscriptionsListen/2026-07-28/subscriptions/acknowledged-first-with-subscriptionId-in-meta"),
		S("subscriptions-ack-reports-agreed-subset", "mcpserver.TestSubscriptionsListen/2026-07-28/subscriptions/acknowledged-first-with-subscriptionId-in-meta"),
		S("subscriptions-tag-every-notification", "mcpserver.TestSubscriptionsListen/2026-07-28/subscriptions/every-notification-carries-the-subscriptionId", "mcpserver.TestSubscriptionsListen/2026-07-28/subscriptions/concurrent-listens-are-kept-apart"),
		S("subscriptions-only-requested-types", "mcpserver.TestSubscriptionsListen/2026-07-28/subscriptions/unrequested-type-is-never-sent", "mcpserver.TestSubscriptionsListen/2026-07-28/subscriptions/concurrent-listens-are-kept-apart"),
		S("subscriptions-request-scoped-not-on-listen", "mcpserver.TestSubscriptionsListen/2026-07-28/subscriptions/unrequested-type-is-never-sent"),
		S("subscriptions-server-teardown-respond", "mcpserver.TestSubscriptionsListen/2026-07-28/subscriptions/server-teardown-sends-cancelled-then-result"),
		S("subscriptions-listen-result-meta", "mcpserver.TestSubscriptionsListen/2026-07-28/subscriptions/server-teardown-sends-cancelled-then-result"),
		S("subscriptions-list-changed-via-listen", "mcpserver.TestHTTPListenIsAStream/2026-07-28/subscriptions/http-listen-response-is-an-open-sse-stream"),
		S("subscriptions-list-changed-via-listen", "conformance.TestTransportServer/2026-07-28/transport-streamable-http/streamable-http-sse-notifications-must-relate"),
		SReq("conformance.TestStatefulServer",
			"tasks-protocol-errors",
			"tasks-input-request-related-task",
			"tasks-result-response-related-task",
			"tasks-related-task-all-messages",
			"elicitation-task-related-id-shared",
			"tasks-delete-after-ttl",
			"subscriptions-list-changed-should-notify",
			"subscriptions-resources-updated-only-if-subscribed",
			"tasks-begin-working",
			"tasks-timestamps",
			"tasks-poll-interval",
			"tasks-return-createtaskresult",
			"tasks-id-string-receiver-unique",
			"tasks-unbound-secure-ids",
			"tasks-ttl-override-report",
			"tasks-requestor-may-ttl",
			"tasks-result-terminal-final",
			"tasks-result-blocks",
			"tasks-result-exact",
			"tasks-sse-no-upgrade-get",
			"tasks-no-related-task-in-get-list-cancel-results",
			"tasks-taskid-param-authoritative",
			"tasks-terminal-immutable",
			"tasks-valid-transitions",
			"tasks-leave-input-required",
			"tasks-input-required-move",
			"tasks-cancel-transition-before-response",
			"tasks-cancelled-sticky",
			"tasks-cancelled-may-delete",
			"tasks-informative-errors",
			"tasks-result-same-error",
			"tasks-list-paginate",
			"tasks-declare-capability",
			"tasks-receiver-without-cap-ignore",
			"tasks-augment-only-if-declared",
			"tasks-no-capability-no-tasks",
			"tasks-status-notification-no-related-task",
			"tasks-cancel-terminal-reject",
			"tasks-tool-forbidden-default",
			"ext-tasks-get-input-requests",
			"caching-ttl-non-negative",
			"mrtr-at-least-one-field",
			"mrtr-inputrequests-keys-values",
			"mrtr-input-request-type-restricted",
			"mrtr-only-declared-capabilities",
			"mrtr-supported-requests-only",
			"mrtr-server-validate-responses",
		),
		CReq("conformance.TestStatefulClient",
			"tasks-augment-only-if-declared",
			"tasks-no-capability-no-tasks",
			"tasks-tool-no-cap-no-augment",
			"tasks-status-notification-optional",
			"mrtr-client-echo-state",
			"mrtr-client-fulfil-before-retry",
			"mrtr-new-id-on-retry",
			"mrtr-no-cross-request-use",
			"mrtr-requeststate-opaque-client",
			"caching-no-cache-mrtr-retries",
			"caching-ttl-not-poll",
		),
	)
	registerGaps(
		Gap{ID: "tasks-get-implies-list", Side: Server, Issue: "#209", Why: "a task started on a connection without an identity can be read by tasks/get and is never listed"},
		Gap{ID: "tasks-failed-status-message", Side: Server, Issue: "#209", Why: "a task failed by an isError tool result carries no statusMessage"},
		Gap{ID: "tasks-document-unbound", Side: Server, Issue: "#209", Why: "nothing user-facing documents that an unowned task is reachable by anyone holding its id"},
		Gap{ID: "tasks-rate-limit", Side: Server, Issue: "#209", Why: "tasks/* has no rate limit"},
		Gap{ID: "tasks-resource-limits", Side: Server, Issue: "#209", Why: "no maximum ttl and no cap on concurrent tasks per requestor"},
		Gap{ID: "tasks-audit", Side: Server, Issue: "#209", Why: "task creation, completion and retrieval are not logged"},
		Gap{ID: "ext-tasks-cancel-cooperative", Side: Server, Issue: "#209", Why: "tasks/cancel forces the cancelled status rather than letting the work reach its own terminal status"},
		Gap{ID: "ext-tasks-durable-before-response", Side: Server, Issue: "#209", Why: "the task store is an in-memory map; a task does not survive the daemon"},
		Gap{ID: "caching-ttl-zero-stale", Side: Client, Issue: "#200", Why: "the client ignores ttlMs and cacheScope; the pool keeps upstream lists until list_changed or restart"},
		Gap{ID: "caching-ttl-positive-fresh", Side: Client, Issue: "#200", Why: "the client ignores ttlMs and cacheScope; the pool keeps upstream lists until list_changed or restart"},
		Gap{ID: "caching-ttl-absent-zero", Side: Client, Issue: "#200", Why: "the client ignores ttlMs and cacheScope; the pool keeps upstream lists until list_changed or restart"},
		Gap{ID: "caching-ttl-negative-zero", Side: Client, Issue: "#200", Why: "the client ignores ttlMs and cacheScope; the pool keeps upstream lists until list_changed or restart"},
		Gap{ID: "caching-stale-refetch", Side: Client, Issue: "#200", Why: "the client ignores ttlMs and cacheScope; the pool keeps upstream lists until list_changed or restart"},
		Gap{ID: "caching-may-refetch-early-serve-stale", Side: Client, Issue: "#200", Why: "the client ignores ttlMs and cacheScope; the pool keeps upstream lists until list_changed or restart"},
		Gap{ID: "caching-page-refetch", Side: Client, Issue: "#200", Why: "the client ignores ttlMs and cacheScope; the pool keeps upstream lists until list_changed or restart"},
		Gap{ID: "caching-key-method-params", Side: Client, Issue: "#200", Why: "the client ignores ttlMs and cacheScope; the pool keeps upstream lists until list_changed or restart"},
		Gap{ID: "caching-private-no-cross-auth", Side: Client, Issue: "#200", Why: "cacheScope is ignored, so a private upstream list is served to every downstream caller"},
		Gap{ID: "caching-notification-invalidates", Side: Client, Issue: "#257", Why: "unverified since subscriptions/listen landed upstream (#239): nothing tests that a modern list_changed empties the pool list cache"},
	)
}
