package e2e_test

import (
	"encoding/json"
	"strings"
	"testing"

	"github.com/dezren39/mcpx/internal/api"
)

// The second instance of the defect above, found by reviewing the first.
//
// `--json for the response as JSON` was printed in the usage of all 22
// generated commands and honoured by 19 of them. printOp writes a Text
// operation's bytes as they came and returns before it reads a.JSON, and a
// streaming operation returns from runOp without reaching printOp at all, so
// `mcpx globals --json` printed TypeScript and `mcpx artifact get X --json`
// printed the artifact. Against the real binary before the fix:
//
//	$ mcpx globals -h | tail -1
//	  --json for the response as JSON; `mcpx help globals` for the settings it reads.
//	$ mcpx globals --json | head -1
//	// Generated by mcpx. Ambient declarations for the globals the runner
//
// There is no JSON form of those responses on /v1 either -- the routes serve
// text/plain -- so the fix is to stop promising one rather than to invent it.
//
// Driven through the binary rather than asserted against the usage string in
// process, because what is being tested is what a person is told when they
// type -h.
func TestAGeneratedCommandPromisesJSONOnlyWhereItDeliversIt(t *testing.T) {
	e := newEnv(t, oneServer)
	promising, silent := 0, 0
	for _, op := range api.Ops() {
		if !op.GeneratedCommand() {
			continue
		}
		usage, _ := e.try(append(append([]string{}, op.CLIWords()...), "-h")...)
		// printOp reads a.JSON for exactly the operations that are neither
		// text nor a stream.
		delivers := !op.Text && !op.Streams
		if promises := strings.Contains(usage, "--json"); promises != delivers {
			verb := "promises --json and does not honour it"
			if delivers {
				verb = "honours --json and does not say so"
			}
			t.Errorf("mcpx %s %s (Text=%v Streams=%v):\n%s",
				strings.Join(op.CLIWords(), " "), verb, op.Text, op.Streams, usage)
		}
		if delivers {
			promising++
		} else {
			silent++
		}
	}
	// Both arms have to be populated or this test checks one rule twice.
	// `globals` and `artifact get` are Text, `events` streams.
	if promising == 0 || silent == 0 {
		t.Fatalf("the table changed shape and this test checks nothing: "+
			"%d commands should promise --json and %d should not", promising, silent)
	}

	// The promise kept, not just made: a command whose usage advertises
	// --json must answer with JSON. Without this the test above is
	// satisfied by removing the flag from every command.
	var doc map[string]any
	if err := json.Unmarshal([]byte(e.run("--json", "health")), &doc); err != nil {
		t.Fatalf("mcpx health advertises --json and did not answer with JSON: %v", err)
	}
}
