package cli

import (
	"fmt"
	"sort"
	"strings"

	"github.com/dezren39/mcpx/internal/settings"
)

// Completion renders a shell completion script.
//
// Generated from the command table and the setting registry, so a new flag is
// completable the moment it is declared. Hand-written completions are the
// first thing to rot, because nothing fails when they are wrong -- they
// simply stop being helpful, silently.
func Completion(shell string) (string, error) {
	cmds := Commands()
	sch, err := settings.New(settings.Registry())
	if err != nil {
		return "", err
	}

	names := make([]string, 0, len(cmds))
	for _, c := range cmds {
		names = append(names, c.Name)
		names = append(names, c.Aliases...)
	}
	sort.Strings(names)

	switch shell {
	case "bash":
		return bashCompletion(cmds, sch, names), nil
	case "zsh":
		return zshCompletion(cmds, sch), nil
	case "fish":
		return fishCompletion(cmds, sch), nil
	}
	return "", fmt.Errorf("no completion for %q; bash, zsh and fish are available", shell)
}

func flagsFor(sch *settings.Schema, cmd string) []settings.Setting {
	var out []settings.Setting
	for _, s := range sch.ForCommand(cmd) {
		if s.Plumbing {
			// Completable only when explicitly typed. Offering internals in
			// a tab list is how someone sets one by accident.
			continue
		}
		out = append(out, s)
	}
	return out
}

func bashCompletion(cmds []Command, sch *settings.Schema, names []string) string {
	var b strings.Builder
	b.WriteString("# mcpx bash completion, generated by `mcpx completion bash`.\n")
	b.WriteString("_mcpx() {\n")
	b.WriteString("  local cur prev cmd\n")
	b.WriteString(`  cur="${COMP_WORDS[COMP_CWORD]}"` + "\n")
	b.WriteString(`  prev="${COMP_WORDS[COMP_CWORD-1]}"` + "\n")
	b.WriteString(`  cmd="${COMP_WORDS[1]}"` + "\n\n")
	fmt.Fprintf(&b, "  local commands=%q\n", strings.Join(names, " "))
	b.WriteString("  if [ \"$COMP_CWORD\" -eq 1 ]; then\n")
	b.WriteString("    COMPREPLY=( $(compgen -W \"$commands\" -- \"$cur\") )\n")
	b.WriteString("    return\n  fi\n\n")

	b.WriteString("  case \"$cmd\" in\n")
	for _, c := range cmds {
		var flags []string
		for _, s := range flagsFor(sch, c.Name) {
			flags = append(flags, "--"+s.FlagName())
			for _, a := range s.FlagAliases {
				flags = append(flags, "--"+a)
			}
		}
		sort.Strings(flags)
		fmt.Fprintf(&b, "    %s) COMPREPLY=( $(compgen -W %q -- \"$cur\") ) ;;\n",
			c.Name, strings.Join(flags, " "))
	}
	b.WriteString("  esac\n}\n")
	b.WriteString("complete -o default -F _mcpx mcpx\n")
	return b.String()
}

func zshCompletion(cmds []Command, sch *settings.Schema) string {
	var b strings.Builder
	b.WriteString("#compdef mcpx\n")
	b.WriteString("# Generated by `mcpx completion zsh`.\n\n")
	b.WriteString("_mcpx() {\n  local -a commands\n  commands=(\n")
	for _, c := range cmds {
		fmt.Fprintf(&b, "    %s:%s\n", c.Name, zshEscape(c.Summary))
	}
	b.WriteString("  )\n\n")
	b.WriteString("  if (( CURRENT == 2 )); then\n")
	b.WriteString("    _describe -t commands 'mcpx command' commands\n")
	b.WriteString("    return\n  fi\n\n")
	b.WriteString("  case \"${words[2]}\" in\n")
	for _, c := range cmds {
		fmt.Fprintf(&b, "    %s)\n      _arguments \\\n", c.Name)
		for _, s := range flagsFor(sch, c.Name) {
			// The description is carried into the completion, so the shell
			// explains a flag at the point of typing it rather than sending
			// the reader to --help.
			if len(s.Enum) > 0 {
				fmt.Fprintf(&b, "        '--%s=[%s]:value:(%s)' \\\n",
					s.FlagName(), zshEscape(s.Short), strings.Join(s.Enum, " "))
				continue
			}
			if s.Kind == settings.KindBool {
				fmt.Fprintf(&b, "        '--%s[%s]' \\\n", s.FlagName(), zshEscape(s.Short))
				continue
			}
			fmt.Fprintf(&b, "        '--%s=[%s]:value:_files' \\\n",
				s.FlagName(), zshEscape(s.Short))
		}
		b.WriteString("        '*:file:_files'\n      ;;\n")
	}
	b.WriteString("  esac\n}\n\n_mcpx \"$@\"\n")
	return b.String()
}

func fishCompletion(cmds []Command, sch *settings.Schema) string {
	var b strings.Builder
	b.WriteString("# Generated by `mcpx completion fish`.\n")
	b.WriteString("complete -c mcpx -f\n")
	for _, c := range cmds {
		fmt.Fprintf(&b, "complete -c mcpx -n __fish_use_subcommand -a %s -d %s\n",
			c.Name, fishQuote(c.Summary))
	}
	for _, c := range cmds {
		for _, s := range flagsFor(sch, c.Name) {
			line := fmt.Sprintf("complete -c mcpx -n '__fish_seen_subcommand_from %s' -l %s -d %s",
				c.Name, s.FlagName(), fishQuote(s.Short))
			if len(s.Enum) > 0 {
				line += fmt.Sprintf(" -a %s", fishQuote(strings.Join(s.Enum, " ")))
			}
			if s.Kind != settings.KindBool {
				line += " -r"
			}
			b.WriteString(line + "\n")
		}
	}
	return b.String()
}

func zshEscape(s string) string {
	s = strings.ReplaceAll(s, `'`, `'\''`)
	s = strings.ReplaceAll(s, "[", `\[`)
	s = strings.ReplaceAll(s, "]", `\]`)
	s = strings.ReplaceAll(s, ":", `\:`)
	return s
}

func fishQuote(s string) string {
	return "'" + strings.ReplaceAll(s, "'", `\'`) + "'"
}
