package cli

import (
	"fmt"
	"regexp"
	"sort"
	"strings"

	"github.com/dezren39/mcpx/internal/api"
	"github.com/dezren39/mcpx/internal/mcpserver"
)

// PluginMethod is a hand-written DaemonClient method and the operation its
// doc comment says it performs.
type PluginMethod struct {
	Method string
	Op     string
}

// pluginOpTag finds `@op name` in a doc comment and the method declared
// after it.
var pluginOpTag = regexp.MustCompile(`@op ([a-z_]+)\n(?:\s*\*[^\n]*\n)*?\s*\*/\n\s*(?:async\s+)?([A-Za-z]+)\(`)

// PluginMethods reads the named methods out of daemon.ts. Read from the
// source because the TypeScript is the declaration; a Go list of the same
// names would be a second copy for the first rename to break.
func PluginMethods(daemonTS string) []PluginMethod {
	var out []PluginMethod
	for _, m := range pluginOpTag.FindAllStringSubmatch(daemonTS, -1) {
		out = append(out, PluginMethod{Op: m[1], Method: m[2]})
	}
	return out
}

// ParityDoc renders docs/parity.md from the declarations the four surfaces
// are built from: the ops table, the command table, the MCP tool list and
// the plugin's methods.
//
// It used to be written by hand, and it stopped rather than drifted: 33 rows
// against 60 operations, with whole families -- artifacts, ask, recipes,
// settings, servers -- missing, and a "Known gaps" section that could not
// say which of its gaps were known. A generated table cannot omit an
// operation, and TestParityDocumentIsCurrent fails when this one is stale.
func ParityDoc(daemonTS string) string {
	ops := api.Ops()
	named := map[string][]string{}
	for _, m := range PluginMethods(daemonTS) {
		named[m.Op] = append(named[m.Op], "`"+m.Method+"()`")
	}
	var b strings.Builder
	b.WriteString(`# Parity

> Everything the CLI can do can be done from a plugin, can be done over
> ` + "`/v1`" + `, can be done from MCP.

<!-- Generated by ParityDoc in internal/cli/parity.go. Do not edit by hand:
     go test ./internal/cli -run TestParityDocumentIsCurrent -update -->

That is a claim, and this file is generated from the four declarations it is
about, so it cannot describe a surface that does not exist or leave one out.
Each direction is also held by a test:

| Direction | Held by |
| --- | --- |
| every ` + "`/v1`" + ` route has an operation, and every operation a route | ` + "`TestEveryDaemonRouteIsDeclared`, `TestEveryDeclaredOpHasARoute`" + ` |
| every operation that is not a stream has an MCP tool | ` + "`TestEveryNonStreamingOpIsReachableAsAnMCPTool`" + ` |
| every operation has a CLI command, and the generated ones reach their route | ` + "`TestEveryOperationIsReachableFromTheCLI`, `TestEveryGeneratedCommandReachesItsRoute`" + ` |
| every command the binary runs is declared, and every declared one runs | ` + "`TestEveryDispatchedCommandIsDeclared`" + ` |
| every command reaches an operation, or says why it cannot | ` + "`TestEveryCommandReachesAnOperationOrSaysWhy`" + ` |
| every operation has a plugin method, and they work against a real daemon | ` + "`TestPluginOpsAreGenerated`, `TestThePluginSuiteRunsAgainstARealDaemon`" + ` |
| this file | ` + "`TestParityDocumentIsCurrent`" + ` |

A command marked *generated* is built from the operation's declaration --
flags from its parameters, positionals for its path -- so it exists the
moment the operation does. The plugin reaches every operation through
` + "`DaemonClient.ops`" + ` (` + "`plugin/opencode/mcpx/ops.gen.ts`" + `, generated the same way);
the named methods beside it are conveniences with typed answers.

Privileged operations are offered rather than hidden. A caller that can reach
the socket can already stop the daemon, so withholding the tool buys no safety
and costs an agent the ability to restart a server that has wedged. What they
carry instead is a description that says so and MCP annotations
(` + "`readOnlyHint`, `destructiveHint`" + `) for a client that wants to scope on them.

`)
	fmt.Fprintf(&b, "## /v1 operations (%d)\n\n", len(ops))
	b.WriteString("| Operation | Route | CLI | MCP tool | Plugin | Notes |\n| --- | --- | --- | --- | --- | --- |\n")
	for _, op := range ops {
		cli := "`mcpx " + strings.Join(op.CLIWords(), " ") + "`"
		if op.GeneratedCommand() {
			cli += " *generated*"
		}
		tool := "`" + op.ToolName() + "`"
		if op.Streams {
			tool = "none: a stream; MCP carries it as `subscriptions/listen`"
		}
		plugin := append([]string{"`ops." + api.TSMethod(op.Name) + "()`"}, named[op.Name]...)
		var notes []string
		if op.Admin {
			notes = append(notes, "Privileged.")
		}
		if op.Destructive {
			notes = append(notes, "Destructive.")
		}
		if op.Streams {
			notes = append(notes, "Never ends; read it until you are done.")
		}
		fmt.Fprintf(&b, "| `%s` | `%s %s` | %s | %s | %s | %s |\n",
			op.Name, op.Method, op.Path, cli, tool, strings.Join(plugin, ", "), strings.Join(notes, " "))
	}

	cmds := Commands()
	sort.Slice(cmds, func(i, j int) bool { return cmds[i].Name < cmds[j].Name })
	reach := commandOps()
	fmt.Fprintf(&b, "\n## CLI commands (%d)\n\n", len(cmds))
	b.WriteString("Every command the binary dispatches, with the operations it reaches. A command\n" +
		"that reaches none says why: those are decisions, not gaps.\n\n")
	b.WriteString("| Command | Operations | Notes |\n| --- | --- | --- |\n")
	for _, c := range cmds {
		name := "`" + c.Name + "`"
		for _, a := range c.Aliases {
			name += " / `" + a + "`"
		}
		var names []string
		for _, op := range reach[c.Name] {
			names = append(names, "`"+op+"`")
		}
		opsCol := strings.Join(names, ", ")
		if opsCol == "" {
			opsCol = "–"
		}
		note := c.Local
		if c.Group == "operations" {
			note = "Generated from the operation table."
		}
		fmt.Fprintf(&b, "| %s | %s | %s |\n", name, opsCol, note)
	}

	// MCP tools that are not a proxy of one operation.
	covering := map[string][]string{}
	for _, op := range ops {
		if op.CoveredBy != "" {
			covering[op.CoveredBy] = append(covering[op.CoveredBy], "`"+op.Name+"`")
		}
	}
	generated := map[string]bool{}
	for _, op := range ops {
		if op.Generated() {
			generated[op.ToolName()] = true
		}
	}
	var hand []mcpserver.Tool
	for _, t := range mcpserver.New(nil, "mcpx", "parity").Tools() {
		if !generated[t.Name] {
			hand = append(hand, t)
		}
	}
	sort.Slice(hand, func(i, j int) bool { return hand[i].Name < hand[j].Name })
	fmt.Fprintf(&b, "\n## Hand-written MCP tools (%d)\n\n", len(hand))
	b.WriteString("The tools mcpx offered before the operation table existed. Where one already\n" +
		"covers an operation, no second tool is generated for it.\n\n")
	b.WriteString("| Tool | Covers | Summary |\n| --- | --- | --- |\n")
	for _, t := range hand {
		cov := strings.Join(covering[t.Name], ", ")
		if cov == "" {
			cov = "–"
		}
		fmt.Fprintf(&b, "| `%s` | %s | %s |\n", t.Name, cov, strings.ReplaceAll(firstSentenceOf(t.Description), "|", "\\|"))
	}

	bounds := api.Boundaries()
	fmt.Fprintf(&b, "\n## Boundaries (%d)\n\n", len(bounds))
	b.WriteString("Every restriction mcpx declares, and whether anything enforces it\n" +
		"([decisions/0003](decisions/0003-declared-vs-enforced-capabilities.md)). An enforced\n" +
		"one names the tests that try to get round it; an advisory one names the issue\n" +
		"that will enforce it. `TestEveryEnforcedBoundaryNamesItsRefusal` holds both.\n\n")
	b.WriteString("| Restriction | Declares | State | Evidence |\n| --- | --- | --- | --- |\n")
	for _, bd := range bounds {
		evidence := bd.Until
		if bd.State == api.Enforced {
			var names []string
			for _, r := range bd.Refusals {
				names = append(names, "`"+r+"`")
			}
			evidence = strings.Join(names, ", ")
		}
		fmt.Fprintf(&b, "| `%s` | %s | **%s** | %s |\n", bd.Name, bd.Declares, bd.State, evidence)
	}
	return b.String()
}

// commandOps maps each command to the operations it is the CLI for.
func commandOps() map[string][]string {
	out := map[string][]string{}
	for _, op := range api.Ops() {
		first := op.CLIWords()[0]
		out[first] = append(out[first], op.Name)
	}
	return out
}

func firstSentenceOf(s string) string {
	s = strings.TrimSpace(strings.ReplaceAll(s, "\n", " "))
	if i := strings.Index(s, ". "); i > 0 {
		return s[:i+1]
	}
	return s
}
