CREATE TABLE graph (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    graph_id UUID REFERENCES graph(id),
    parent_id UUID REFERENCES graph(id),
    kind JSON,
    scope JSON,
    alias JSON,
    content JSON,
    arguments JSON,
    properties JSON,
    acl JSON,
    public JSON,
    unlisted JSON,
    personal JSON,
    owners JSON,
    admins JSON,
    note JSON,
    created_at TIMESTAMPTZ DEFAULT now(),
    created_by JSON,
    updated_at TIMESTAMPTZ DEFAULT now(),
    updated_by JSON
);

CREATE TABLE nodes (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    graph_id UUID REFERENCES graph(id),
    parent_id UUID REFERENCES nodes(id),
    kind JSON,
    scope JSON,
    alias JSON,
    content JSON,
    arguments JSON,
    properties JSON,
    acl JSON,
    public JSON,
    unlisted JSON,
    personal JSON,
    owners JSON,
    admins JSON,
    note JSON,
    created_at TIMESTAMPTZ DEFAULT now(),
    created_by JSON,
    updated_at TIMESTAMPTZ DEFAULT now(),
    updated_by JSON
);

CREATE TABLE identifiers (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    graph_id UUID REFERENCES graph(id),
    parent_id UUID REFERENCES identifiers(id),
    kind JSON,
    scope JSON,
    alias JSON,
    content JSON,
    arguments JSON,
    properties JSON,
    acl JSON,
    public JSON,
    unlisted JSON,
    personal JSON,
    owners JSON,
    admins JSON,
    note JSON,
    created_at TIMESTAMPTZ DEFAULT now(),
    created_by JSON,
    updated_at TIMESTAMPTZ DEFAULT now(),
    updated_by JSON
);

CREATE TABLE nodes_identifiers (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    graph_id UUID REFERENCES graph(id),
    parent_id UUID REFERENCES nodes_identifiers(id),
    kind JSON,
    scope JSON,
    alias JSON,
    content JSON,
    arguments JSON,
    properties JSON,
    acl JSON,
    public JSON,
    unlisted JSON,
    personal JSON,
    owners JSON,
    admins JSON,
    note JSON,
    identifier_id UUID REFERENCES identifiers(id),
    node_id UUID NULL REFERENCES nodes(id),
    created_at TIMESTAMPTZ DEFAULT now(),
    created_by JSON,
    updated_at TIMESTAMPTZ DEFAULT now(),
    updated_by JSON
);

CREATE TABLE links (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    graph_id UUID REFERENCES graph(id),
    parent_id UUID REFERENCES links(id),
    kind JSON,
    scope JSON,
    alias JSON,
    content JSON,
    arguments JSON,
    properties JSON,
    acl JSON,
    public JSON,
    unlisted JSON,
    personal JSON,
    owners JSON,
    admins JSON,
    note JSON,
    element_identifier_id UUID REFERENCES identifiers(id),
    partner_identifier_id UUID REFERENCES identifiers(id),
    created_at TIMESTAMPTZ DEFAULT now(),
    created_by JSON,
    updated_at TIMESTAMPTZ DEFAULT now(),
    updated_by JSON
);

CREATE TABLE links_identifiers (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    graph_id UUID REFERENCES graph(id),
    parent_id UUID REFERENCES links_identifiers(id),
    kind JSON,
    scope JSON,
    alias JSON,
    content JSON,
    arguments JSON,
    properties JSON,
    acl JSON,
    public JSON,
    unlisted JSON,
    personal JSON,
    owners JSON,
    admins JSON,
    note JSON,
    identifier_id UUID REFERENCES identifiers(id),
    link_id UUID NULL REFERENCES links(id),
    created_at TIMESTAMPTZ DEFAULT now(),
    created_by JSON,
    updated_at TIMESTAMPTZ DEFAULT now(),
    updated_by JSON
);
