// Code generated by mcpx from internal/api, the /v1 operation table. DO NOT EDIT.
// Regenerate with: go test ./internal/api -run TestPluginOpsAreGenerated -update
//
// One typed method per operation. The request is assembled from the same
// declaration the daemon's routes, the MCP tools and the CLI commands are, so
// a parameter this file sends is one the route reads.

/** Where a parameter travels. */
type In = "path" | "query" | "body"

type ParamSpec = { in: In; required?: boolean; raw?: boolean }

type OpSpec = {
  method: string
  path: string
  params: Record<string, ParamSpec>
  /** The body parameter that is the whole body, for routes that take a bare document. */
  wrap?: string
  /** json is parsed; response is handed back for the caller to read as text, bytes or a stream. */
  response: "json" | "response"
}

/** Every /v1 operation, by name. */
export const OPS: Record<string, OpSpec> = {
  artifact_delete: {
    method: "DELETE",
    path: "/v1/artifacts/{id}",
    params: {
      id: { in: "path", required: true },
    },
    response: "json",
  },
  artifact_get: {
    method: "GET",
    path: "/v1/artifacts/{id}",
    params: {
      id: { in: "path", required: true },
    },
    response: "response",
  },
  artifact_put: {
    method: "POST",
    path: "/v1/artifacts",
    params: {
      name: { in: "query", required: true },
      mime: { in: "query" },
      run: { in: "query" },
      session: { in: "query" },
      ttl: { in: "query" },
      content: { in: "body", required: true, raw: true },
    },
    response: "json",
  },
  artifacts_list: {
    method: "GET",
    path: "/v1/artifacts",
    params: {
      run: { in: "query" },
      session: { in: "query" },
      limit: { in: "query" },
    },
    response: "json",
  },
  ask_abandon: {
    method: "POST",
    path: "/v1/ask/{id}/abandon",
    params: {
      id: { in: "path", required: true },
    },
    response: "json",
  },
  ask_answers: {
    method: "POST",
    path: "/v1/ask/{id}/answers",
    params: {
      id: { in: "path", required: true },
      answers: { in: "body", required: true },
    },
    response: "json",
  },
  ask_begin: {
    method: "POST",
    path: "/v1/ask",
    params: {
      kind: { in: "body", required: true },
      server: { in: "body", required: true },
      tool: { in: "body" },
      name: { in: "body" },
      uri: { in: "body" },
      args: { in: "body" },
      arguments: { in: "body" },
      ttl: { in: "body" },
      session: { in: "body" },
      context: { in: "body" },
    },
    response: "json",
  },
  ask_poll: {
    method: "GET",
    path: "/v1/ask/{id}",
    params: {
      id: { in: "path", required: true },
      waitMs: { in: "query" },
    },
    response: "json",
  },
  batch: {
    method: "POST",
    path: "/v1/batch",
    params: {
      calls: { in: "body", required: true },
      stopOnError: { in: "body" },
      parallel: { in: "body" },
      session: { in: "body" },
      context: { in: "body" },
    },
    response: "json",
  },
  call: {
    method: "POST",
    path: "/v1/call",
    params: {
      server: { in: "body", required: true },
      tool: { in: "body", required: true },
      args: { in: "body" },
      task: { in: "body" },
      session: { in: "body" },
      context: { in: "body" },
    },
    response: "json",
  },
  call_path: {
    method: "POST",
    path: "/v1/call/{server}/{tool}",
    params: {
      server: { in: "path", required: true },
      tool: { in: "path", required: true },
      session: { in: "query" },
      arguments: { in: "body" },
    },
    wrap: "arguments",
    response: "json",
  },
  catalog: {
    method: "GET",
    path: "/v1/catalog",
    params: {
      ns: { in: "query" },
      budget: { in: "query" },
      bias: { in: "query" },
      profile: { in: "query" },
      skipDefault: { in: "query" },
      allProfiles: { in: "query" },
    },
    response: "response",
  },
  catalog_history: {
    method: "GET",
    path: "/v1/catalog/history",
    params: {
      tool: { in: "query" },
    },
    response: "json",
  },
  chat_completions: {
    method: "POST",
    path: "/v1/chat/completions",
    params: {
      model: { in: "body" },
      messages: { in: "body", required: true },
    },
    response: "json",
  },
  client_module: {
    method: "GET",
    path: "/v1/client.ts",
    params: {
      ns: { in: "query" },
      session: { in: "query" },
      profile: { in: "query" },
      skipDefault: { in: "query" },
      allProfiles: { in: "query" },
    },
    response: "response",
  },
  complete: {
    method: "POST",
    path: "/v1/complete",
    params: {
      server: { in: "body", required: true },
      ref: { in: "body", required: true },
      argument: { in: "body", required: true },
      arguments: { in: "body" },
      session: { in: "body" },
      context: { in: "body" },
    },
    response: "json",
  },
  daemon_restart: {
    method: "POST",
    path: "/v1/daemon/restart",
    params: {},
    response: "json",
  },
  dashboard: {
    method: "GET",
    path: "/v1/dashboard",
    params: {},
    response: "response",
  },
  diagnose: {
    method: "POST",
    path: "/v1/diagnose",
    params: {
      source: { in: "body", required: true },
      session: { in: "body" },
      repair: { in: "body" },
    },
    response: "json",
  },
  elicit_answer: {
    method: "POST",
    path: "/v1/elicit/{id}/{action}",
    params: {
      id: { in: "path", required: true },
      action: { in: "path", required: true },
      content: { in: "body" },
    },
    wrap: "content",
    response: "json",
  },
  elicit_get: {
    method: "GET",
    path: "/v1/elicit/{id}",
    params: {
      id: { in: "path", required: true },
    },
    response: "json",
  },
  elicit_list: {
    method: "GET",
    path: "/v1/elicit",
    params: {
      session: { in: "query" },
      audience: { in: "query" },
    },
    response: "json",
  },
  embeddings: {
    method: "POST",
    path: "/v1/embeddings",
    params: {
      input: { in: "body", required: true },
      model: { in: "body" },
    },
    response: "json",
  },
  embeddings_export: {
    method: "GET",
    path: "/v1/embeddings/export",
    params: {},
    response: "json",
  },
  embeddings_import: {
    method: "POST",
    path: "/v1/embeddings/import",
    params: {
      content: { in: "body", required: true, raw: true },
    },
    response: "json",
  },
  events: {
    method: "GET",
    path: "/v1/events",
    params: {
      kinds: { in: "query" },
      session: { in: "query" },
      server: { in: "query" },
      uri: { in: "query" },
      since: { in: "query" },
    },
    response: "response",
  },
  exec: {
    method: "POST",
    path: "/v1/exec",
    params: {
      source: { in: "body" },
      file: { in: "body" },
      options: { in: "body" },
    },
    response: "json",
  },
  feedback: {
    method: "POST",
    path: "/v1/feedback",
    params: {
      traceId: { in: "body", required: true },
      score: { in: "body", required: true },
      target: { in: "body" },
      retrievalScore: { in: "body" },
      executionScore: { in: "body" },
      notes: { in: "body" },
    },
    response: "json",
  },
  globals: {
    method: "GET",
    path: "/v1/globals.d.ts",
    params: {
      ns: { in: "query" },
      profile: { in: "query" },
      skipDefault: { in: "query" },
      allProfiles: { in: "query" },
    },
    response: "response",
  },
  health: {
    method: "GET",
    path: "/v1/health",
    params: {},
    response: "json",
  },
  intent: {
    method: "POST",
    path: "/v1/intent",
    params: {
      prompt: { in: "body", required: true },
      autonomy: { in: "body" },
      placeholders: { in: "body" },
      session: { in: "body" },
    },
    response: "json",
  },
  interactions_get: {
    method: "GET",
    path: "/v1/interactions/{id}",
    params: {
      id: { in: "path", required: true },
    },
    response: "json",
  },
  interactions_list: {
    method: "GET",
    path: "/v1/interactions",
    params: {
      q: { in: "query" },
      source: { in: "query" },
      target: { in: "query" },
      hasFeedback: { in: "query" },
    },
    response: "json",
  },
  log_query: {
    method: "GET",
    path: "/v1/log",
    params: {
      since: { in: "query" },
      until: { in: "query" },
      level: { in: "query" },
      event: { in: "query" },
      server: { in: "query" },
      tool: { in: "query" },
      session: { in: "query" },
      trace: { in: "query" },
      chain: { in: "query" },
      grep: { in: "query" },
      limit: { in: "query" },
      reverse: { in: "query" },
    },
    response: "json",
  },
  log_record: {
    method: "POST",
    path: "/v1/log",
    params: {
      level: { in: "query" },
      record: { in: "body", required: true },
    },
    wrap: "record",
    response: "json",
  },
  metrics_tokens: {
    method: "GET",
    path: "/v1/metrics/tokens",
    params: {},
    response: "json",
  },
  metrics_tools: {
    method: "GET",
    path: "/v1/metrics/tools",
    params: {},
    response: "json",
  },
  namespaces: {
    method: "GET",
    path: "/v1/namespaces",
    params: {
      profile: { in: "query" },
      skipDefault: { in: "query" },
      allProfiles: { in: "query" },
    },
    response: "json",
  },
  openapi: {
    method: "GET",
    path: "/v1/openapi.json",
    params: {},
    response: "json",
  },
  prompt_get: {
    method: "POST",
    path: "/v1/prompt",
    params: {
      server: { in: "body", required: true },
      name: { in: "body", required: true },
      arguments: { in: "body" },
      sessionId: { in: "body" },
      callId: { in: "body" },
    },
    response: "json",
  },
  prompts: {
    method: "GET",
    path: "/v1/prompts",
    params: {
      ns: { in: "query" },
    },
    response: "json",
  },
  protocol: {
    method: "GET",
    path: "/v1/protocol",
    params: {},
    response: "json",
  },
  recipe_get: {
    method: "GET",
    path: "/v1/recipes/{name}",
    params: {
      name: { in: "path", required: true },
    },
    response: "json",
  },
  recipe_run: {
    method: "POST",
    path: "/v1/recipes/{name}/run",
    params: {
      name: { in: "path", required: true },
      placeholders: { in: "body" },
      autonomy: { in: "body" },
      session: { in: "body" },
    },
    response: "json",
  },
  recipe_save: {
    method: "POST",
    path: "/v1/recipes/{name}",
    params: {
      name: { in: "path", required: true },
      source: { in: "body", required: true },
      overwrite: { in: "body" },
    },
    response: "json",
  },
  recipes_list: {
    method: "GET",
    path: "/v1/recipes",
    params: {
      q: { in: "query" },
      limit: { in: "query" },
    },
    response: "json",
  },
  refresh: {
    method: "POST",
    path: "/v1/refresh",
    params: {},
    response: "json",
  },
  registry_search: {
    method: "GET",
    path: "/v1/registry/search",
    params: {
      q: { in: "query", required: true },
      limit: { in: "query" },
    },
    response: "json",
  },
  reload: {
    method: "POST",
    path: "/v1/reload",
    params: {},
    response: "json",
  },
  resolve: {
    method: "GET",
    path: "/v1/resolve",
    params: {
      dir: { in: "query", required: true },
    },
    response: "json",
  },
  resource_read: {
    method: "POST",
    path: "/v1/resource",
    params: {
      server: { in: "body", required: true },
      uri: { in: "body", required: true },
      session: { in: "body" },
      context: { in: "body" },
    },
    response: "json",
  },
  resource_templates: {
    method: "GET",
    path: "/v1/resource-templates",
    params: {
      ns: { in: "query" },
    },
    response: "json",
  },
  resources: {
    method: "GET",
    path: "/v1/resources",
    params: {
      ns: { in: "query" },
    },
    response: "json",
  },
  restart: {
    method: "POST",
    path: "/v1/restart",
    params: {
      server: { in: "body" },
      lazy: { in: "body" },
    },
    response: "json",
  },
  search: {
    method: "GET",
    path: "/v1/search",
    params: {
      q: { in: "query", required: true },
      limit: { in: "query" },
      semantic: { in: "query" },
    },
    response: "json",
  },
  servers_add: {
    method: "POST",
    path: "/v1/servers",
    params: {
      name: { in: "body", required: true },
      command: { in: "body" },
      args: { in: "body" },
      env: { in: "body" },
      url: { in: "body" },
      headers: { in: "body" },
      transport: { in: "body" },
      mcpx: { in: "body" },
      scope: { in: "body" },
      replace: { in: "body" },
    },
    response: "json",
  },
  servers_list: {
    method: "GET",
    path: "/v1/servers",
    params: {},
    response: "json",
  },
  servers_remove: {
    method: "DELETE",
    path: "/v1/servers/{name}",
    params: {
      name: { in: "path", required: true },
      scope: { in: "query" },
    },
    response: "json",
  },
  session_release: {
    method: "POST",
    path: "/v1/session/release",
    params: {
      session: { in: "body", required: true },
    },
    response: "json",
  },
  settings_get: {
    method: "GET",
    path: "/v1/settings/{path}",
    params: {
      path: { in: "path", required: true },
    },
    response: "json",
  },
  settings_list: {
    method: "GET",
    path: "/v1/settings",
    params: {
      scope: { in: "query" },
      plumbing: { in: "query" },
      changed: { in: "query" },
    },
    response: "json",
  },
  settings_set: {
    method: "PUT",
    path: "/v1/settings/{path}",
    params: {
      path: { in: "path", required: true },
      value: { in: "body", required: true },
      persist: { in: "body" },
    },
    response: "json",
  },
  settings_unset: {
    method: "DELETE",
    path: "/v1/settings/{path}",
    params: {
      path: { in: "path", required: true },
    },
    response: "json",
  },
  shutdown: {
    method: "POST",
    path: "/v1/shutdown",
    params: {},
    response: "json",
  },
  stats_query: {
    method: "GET",
    path: "/v1/stats",
    params: {
      by: { in: "query" },
      since: { in: "query" },
      until: { in: "query" },
      server: { in: "query" },
      tool: { in: "query" },
      session: { in: "query" },
      top: { in: "query" },
    },
    response: "json",
  },
  status: {
    method: "GET",
    path: "/v1/status",
    params: {},
    response: "json",
  },
  task_cancel: {
    method: "POST",
    path: "/v1/tasks/{id}/cancel",
    params: {
      id: { in: "path", required: true },
    },
    response: "json",
  },
  task_get: {
    method: "GET",
    path: "/v1/tasks/{id}",
    params: {
      id: { in: "path", required: true },
    },
    response: "json",
  },
  task_result: {
    method: "GET",
    path: "/v1/tasks/{id}/result",
    params: {
      id: { in: "path", required: true },
      waitMs: { in: "query" },
    },
    response: "json",
  },
  tasks_list: {
    method: "GET",
    path: "/v1/tasks",
    params: {},
    response: "json",
  },
  tool_invoke: {
    method: "POST",
    path: "/v1/tools/{tool}",
    params: {
      tool: { in: "path", required: true },
      arguments: { in: "body" },
    },
    wrap: "arguments",
    response: "json",
  },
  tools: {
    method: "GET",
    path: "/v1/tools",
    params: {
      ns: { in: "query" },
    },
    response: "json",
  },
  types: {
    method: "GET",
    path: "/v1/types",
    params: {
      ns: { in: "query" },
      instructions: { in: "query" },
      profile: { in: "query" },
      skipDefault: { in: "query" },
      allProfiles: { in: "query" },
    },
    response: "response",
  },
}

/** A refusal from the daemon, with the status and the body kept. */
export class OpError extends Error {
  constructor(
    readonly op: string,
    readonly status: number,
    readonly body: string,
  ) {
    let msg = body.trim()
    try {
      const parsed = JSON.parse(body) as { error?: unknown }
      if (typeof parsed.error === "string" && parsed.error) msg = parsed.error
    } catch {
      // Not JSON; the text is the message.
    }
    super(`mcpx ${op}: ${status}: ${msg}`)
  }
}

const scalar = (v: unknown): string => {
  if (typeof v === "string") return v
  if (typeof v === "boolean") return v ? "1" : "0"
  if (typeof v === "number") return String(v)
  return JSON.stringify(v)
}

/**
 * The path and request for one operation. The same rules as the Go side's
 * Op.Request: path parameters are escaped into the path, query parameters
 * are scalars, a raw parameter is the body as bytes, and everything else is
 * a JSON object -- or, for the routes that take a bare document, that
 * document.
 */
export const buildRequest = (name: string, args: Record<string, unknown> = {}): { path: string; init: RequestInit } => {
  const spec = OPS[name]
  if (!spec) throw new Error(`mcpx: no operation ${name}`)
  let path = spec.path
  const query = new URLSearchParams()
  const body: Record<string, unknown> = {}
  let raw: BodyInit | undefined
  for (const [key, value] of Object.entries(args)) {
    if (value === undefined) continue
    const p = spec.params[key]
    if (!p) throw new Error(`mcpx ${name} takes no argument ${key}`)
    if (p.raw) raw = value as BodyInit
    else if (p.in === "path") path = path.replace(`{${key}}`, encodeURIComponent(scalar(value)))
    else if (p.in === "query") {
      const s = scalar(value)
      if (s !== "") query.set(key, s)
    } else body[key] = value
  }
  for (const [key, p] of Object.entries(spec.params)) {
    if (p.required && args[key] === undefined) throw new Error(`mcpx ${name}: ${key} is required`)
  }
  if (path.includes("{")) throw new Error(`mcpx ${name}: unfilled path parameter in ${path}`)
  const qs = query.toString()
  if (qs) path += "?" + qs
  const init: RequestInit = { method: spec.method }
  if (raw !== undefined) {
    init.body = raw
    init.headers = { "content-type": "application/octet-stream" }
  } else if (spec.method !== "GET") {
    const doc = spec.wrap ? (body[spec.wrap] ?? {}) : body
    init.body = JSON.stringify(doc)
    init.headers = { "content-type": "application/json" }
  }
  return { path, init }
}

/** Sends one request to the daemon; DaemonClient.raw is one. */
export type Fetcher = (path: string, init: RequestInit) => Promise<Response>

/** Options every method accepts. */
export type CallOptions = { signal?: AbortSignal }

/** A typed method for every /v1 operation. */
export class DaemonOps {
  constructor(private readonly fetcher: Fetcher) {}

  /** Performs any operation by name; the typed methods below are this. */
  async invoke(name: string, args: Record<string, unknown> = {}, opts: CallOptions = {}): Promise<unknown> {
    const { path, init } = buildRequest(name, args)
    if (opts.signal) init.signal = opts.signal
    const res = await this.fetcher(path, init)
    if (!res.ok) throw new OpError(name, res.status, await res.text())
    if (OPS[name].response === "response") return res
    const text = await res.text()
    return text ? JSON.parse(text) : undefined
  }

  /**
   * Forget one artifact. `DELETE /v1/artifacts/{id}`.
   * Privileged: it changes the daemon rather than reading it.
   * Destructive: it cannot be undone, and other callers are affected.
   */
  artifactDelete(args: { id: string }, opts: CallOptions = {}): Promise<unknown> {
    return this.invoke("artifact_delete", args, opts) as Promise<unknown>
  }

  /**
   * Fetch one artifact's bytes. `GET /v1/artifacts/{id}`.
   */
  artifactGet(args: { id: string }, opts: CallOptions = {}): Promise<Response> {
    return this.invoke("artifact_get", args, opts) as Promise<Response>
  }

  /**
   * Store a file a script produced. `POST /v1/artifacts`.
   * Privileged: it changes the daemon rather than reading it.
   */
  artifactPut(args: { name: string; mime?: string; run?: string; session?: string; ttl?: string; content: BodyInit }, opts: CallOptions = {}): Promise<unknown> {
    return this.invoke("artifact_put", args, opts) as Promise<unknown>
  }

  /**
   * Files scripts produced, newest first. `GET /v1/artifacts`.
   */
  artifactsList(args: { run?: string; session?: string; limit?: number } = {}, opts: CallOptions = {}): Promise<unknown> {
    return this.invoke("artifacts_list", args, opts) as Promise<unknown>
  }

  /**
   * Give up on a call nobody is going to answer. `POST /v1/ask/{id}/abandon`.
   * Privileged: it changes the daemon rather than reading it.
   * Destructive: it cannot be undone, and other callers are affected.
   */
  askAbandon(args: { id: string }, opts: CallOptions = {}): Promise<unknown> {
    return this.invoke("ask_abandon", args, opts) as Promise<unknown>
  }

  /**
   * Answer the questions a call is waiting on. `POST /v1/ask/{id}/answers`.
   * Privileged: it changes the daemon rather than reading it.
   */
  askAnswers(args: { id: string; answers: Record<string, unknown> }, opts: CallOptions = {}): Promise<unknown> {
    return this.invoke("ask_answers", args, opts) as Promise<unknown>
  }

  /**
   * Start a call that a server may interrupt with a question. `POST /v1/ask`.
   */
  askBegin(args: { kind: "tools/call" | "prompts/get" | "resources/read"; server: string; tool?: string; name?: string; uri?: string; args?: Record<string, unknown>; arguments?: Record<string, unknown>; ttl?: number; session?: string; context?: Record<string, unknown> }, opts: CallOptions = {}): Promise<unknown> {
    return this.invoke("ask_begin", args, opts) as Promise<unknown>
  }

  /**
   * What a call is waiting on, or its result. `GET /v1/ask/{id}`.
   */
  askPoll(args: { id: string; waitMs?: number }, opts: CallOptions = {}): Promise<unknown> {
    return this.invoke("ask_poll", args, opts) as Promise<unknown>
  }

  /**
   * Execute multiple tool calls in a single turn. `POST /v1/batch`.
   */
  batch(args: { calls: unknown[]; stopOnError?: boolean; parallel?: boolean; session?: string; context?: Record<string, unknown> }, opts: CallOptions = {}): Promise<unknown> {
    return this.invoke("batch", args, opts) as Promise<unknown>
  }

  /**
   * Call one tool on one server. `POST /v1/call`.
   */
  call(args: { server: string; tool: string; args?: Record<string, unknown>; task?: Record<string, unknown>; session?: string; context?: Record<string, unknown> }, opts: CallOptions = {}): Promise<unknown> {
    return this.invoke("call", args, opts) as Promise<unknown>
  }

  /**
   * Call one tool, with the pair in the URL. `POST /v1/call/{server}/{tool}`.
   */
  callPath(args: { server: string; tool: string; session?: string; arguments?: Record<string, unknown> }, opts: CallOptions = {}): Promise<unknown> {
    return this.invoke("call_path", args, opts) as Promise<unknown>
  }

  /**
   * Every namespace with as many signatures as fit a token budget. `GET /v1/catalog`.
   */
  catalog(args: { ns?: string; budget?: number; bias?: string; profile?: string; skipDefault?: "0" | "1"; allProfiles?: "0" | "1" } = {}, opts: CallOptions = {}): Promise<Response> {
    return this.invoke("catalog", args, opts) as Promise<Response>
  }

  /**
   * What changed in the tool schemas, and when. `GET /v1/catalog/history`.
   */
  catalogHistory(args: { tool?: string } = {}, opts: CallOptions = {}): Promise<unknown> {
    return this.invoke("catalog_history", args, opts) as Promise<unknown>
  }

  /**
   * OpenAI-compatible LLM chat completions endpoint. `POST /v1/chat/completions`.
   */
  chatCompletions(args: { model?: string; messages: unknown[] }, opts: CallOptions = {}): Promise<unknown> {
    return this.invoke("chat_completions", args, opts) as Promise<unknown>
  }

  /**
   * The generated TypeScript client. `GET /v1/client.ts`.
   */
  clientModule(args: { ns?: string; session?: string; profile?: string; skipDefault?: "0" | "1"; allProfiles?: "0" | "1" } = {}, opts: CallOptions = {}): Promise<Response> {
    return this.invoke("client_module", args, opts) as Promise<Response>
  }

  /**
   * Argument autocomplete from an upstream server. `POST /v1/complete`.
   */
  complete(args: { server: string; ref: Record<string, unknown>; argument: Record<string, unknown>; arguments?: Record<string, unknown>; session?: string; context?: Record<string, unknown> }, opts: CallOptions = {}): Promise<unknown> {
    return this.invoke("complete", args, opts) as Promise<unknown>
  }

  /**
   * Restart the mcpx daemon. `POST /v1/daemon/restart`.
   * Privileged: it changes the daemon rather than reading it.
   * Destructive: it cannot be undone, and other callers are affected.
   */
  daemonRestart(args: Record<string, never> = {}, opts: CallOptions = {}): Promise<unknown> {
    return this.invoke("daemon_restart", args, opts) as Promise<unknown>
  }

  /**
   * Live web dashboard HTML. `GET /v1/dashboard`.
   */
  dashboard(args: Record<string, never> = {}, opts: CallOptions = {}): Promise<Response> {
    return this.invoke("dashboard", args, opts) as Promise<Response>
  }

  /**
   * Explain what is wrong with a script, deterministically. `POST /v1/diagnose`.
   */
  diagnose(args: { source: string; session?: string; repair?: boolean }, opts: CallOptions = {}): Promise<unknown> {
    return this.invoke("diagnose", args, opts) as Promise<unknown>
  }

  /**
   * Answer a question a server asked. `POST /v1/elicit/{id}/{action}`.
   * Privileged: it changes the daemon rather than reading it.
   */
  elicitAnswer(args: { id: string; action: "accept" | "decline" | "cancel"; content?: Record<string, unknown> }, opts: CallOptions = {}): Promise<unknown> {
    return this.invoke("elicit_answer", args, opts) as Promise<unknown>
  }

  /**
   * One question, with its answer once it has one. `GET /v1/elicit/{id}`.
   */
  elicitGet(args: { id: string }, opts: CallOptions = {}): Promise<unknown> {
    return this.invoke("elicit_get", args, opts) as Promise<unknown>
  }

  /**
   * Questions servers are waiting on an answer for. `GET /v1/elicit`.
   */
  elicitList(args: { session?: string; audience?: string } = {}, opts: CallOptions = {}): Promise<unknown> {
    return this.invoke("elicit_list", args, opts) as Promise<unknown>
  }

  /**
   * Compute vector embeddings for text. `POST /v1/embeddings`.
   */
  embeddings(args: { input: string; model?: string }, opts: CallOptions = {}): Promise<unknown> {
    return this.invoke("embeddings", args, opts) as Promise<unknown>
  }

  /**
   * Export cached vector embeddings. `GET /v1/embeddings/export`.
   */
  embeddingsExport(args: Record<string, never> = {}, opts: CallOptions = {}): Promise<unknown> {
    return this.invoke("embeddings_export", args, opts) as Promise<unknown>
  }

  /**
   * Import pre-computed vector embeddings. `POST /v1/embeddings/import`.
   */
  embeddingsImport(args: { content: BodyInit }, opts: CallOptions = {}): Promise<unknown> {
    return this.invoke("embeddings_import", args, opts) as Promise<unknown>
  }

  /**
   * Server-sent event stream. `GET /v1/events`.
   * A stream: read the response body until you are done with it.
   */
  events(args: { kinds?: string; session?: string; server?: string; uri?: string; since?: number } = {}, opts: CallOptions = {}): Promise<Response> {
    return this.invoke("events", args, opts) as Promise<Response>
  }

  /**
   * Run TypeScript on the daemon. `POST /v1/exec`.
   * Privileged: it changes the daemon rather than reading it.
   */
  exec(args: { source?: string; file?: string; options?: Record<string, unknown> } = {}, opts: CallOptions = {}): Promise<unknown> {
    return this.invoke("exec", args, opts) as Promise<unknown>
  }

  /**
   * Submit quality feedback for a trace. `POST /v1/feedback`.
   */
  feedback(args: { traceId: string; score: number; target?: string; retrievalScore?: number; executionScore?: number; notes?: string }, opts: CallOptions = {}): Promise<unknown> {
    return this.invoke("feedback", args, opts) as Promise<unknown>
  }

  /**
   * Ambient declarations for the installed globals. `GET /v1/globals.d.ts`.
   */
  globals(args: { ns?: string; profile?: string; skipDefault?: "0" | "1"; allProfiles?: "0" | "1" } = {}, opts: CallOptions = {}): Promise<Response> {
    return this.invoke("globals", args, opts) as Promise<Response>
  }

  /**
   * Liveness, version and the loopback endpoint. `GET /v1/health`.
   */
  health(args: Record<string, never> = {}, opts: CallOptions = {}): Promise<unknown> {
    return this.invoke("health", args, opts) as Promise<unknown>
  }

  /**
   * A request in words, a script back. `POST /v1/intent`.
   */
  intent(args: { prompt: string; autonomy?: "propose" | "run"; placeholders?: Record<string, unknown>; session?: string }, opts: CallOptions = {}): Promise<unknown> {
    return this.invoke("intent", args, opts) as Promise<unknown>
  }

  /**
   * Inspect a specific interaction trace. `GET /v1/interactions/{id}`.
   */
  interactionsGet(args: { id: string }, opts: CallOptions = {}): Promise<unknown> {
    return this.invoke("interactions_get", args, opts) as Promise<unknown>
  }

  /**
   * List and filter past interaction traces. `GET /v1/interactions`.
   */
  interactionsList(args: { q?: string; source?: string; target?: string; hasFeedback?: string } = {}, opts: CallOptions = {}): Promise<unknown> {
    return this.invoke("interactions_list", args, opts) as Promise<unknown>
  }

  /**
   * Query the durable log. `GET /v1/log`.
   */
  logQuery(args: { since?: string; until?: string; level?: "debug" | "info" | "warn" | "error"; event?: string; server?: string; tool?: string; session?: string; trace?: string; chain?: string; grep?: string; limit?: number; reverse?: "0" | "1" } = {}, opts: CallOptions = {}): Promise<unknown> {
    return this.invoke("log_query", args, opts) as Promise<unknown>
  }

  /**
   * Append one record to the durable log. `POST /v1/log`.
   * Privileged: it changes the daemon rather than reading it.
   */
  logRecord(args: { level?: "debug" | "info" | "warn" | "error"; record: Record<string, unknown> }, opts: CallOptions = {}): Promise<unknown> {
    return this.invoke("log_record", args, opts) as Promise<unknown>
  }

  /**
   * Token economics telemetry summary. `GET /v1/metrics/tokens`.
   */
  metricsTokens(args: Record<string, never> = {}, opts: CallOptions = {}): Promise<unknown> {
    return this.invoke("metrics_tokens", args, opts) as Promise<unknown>
  }

  /**
   * Tool call telemetry, error rates, correlations and timelines. `GET /v1/metrics/tools`.
   */
  metricsTools(args: Record<string, never> = {}, opts: CallOptions = {}): Promise<unknown> {
    return this.invoke("metrics_tools", args, opts) as Promise<unknown>
  }

  /**
   * Every configured server, with tool counts. `GET /v1/namespaces`.
   */
  namespaces(args: { profile?: string; skipDefault?: "0" | "1"; allProfiles?: "0" | "1" } = {}, opts: CallOptions = {}): Promise<unknown> {
    return this.invoke("namespaces", args, opts) as Promise<unknown>
  }

  /**
   * This API, as an OpenAPI 3.1 document. `GET /v1/openapi.json`.
   */
  openapi(args: Record<string, never> = {}, opts: CallOptions = {}): Promise<unknown> {
    return this.invoke("openapi", args, opts) as Promise<unknown>
  }

  /**
   * Render one prompt with its arguments filled in. `POST /v1/prompt`.
   */
  promptGet(args: { server: string; name: string; arguments?: Record<string, unknown>; sessionId?: string; callId?: string }, opts: CallOptions = {}): Promise<unknown> {
    return this.invoke("prompt_get", args, opts) as Promise<unknown>
  }

  /**
   * Every prompt the configured servers offer. `GET /v1/prompts`.
   */
  prompts(args: { ns?: string } = {}, opts: CallOptions = {}): Promise<unknown> {
    return this.invoke("prompts", args, opts) as Promise<unknown>
  }

  /**
   * Which MCP revisions mcpx speaks, in both directions. `GET /v1/protocol`.
   */
  protocol(args: Record<string, never> = {}, opts: CallOptions = {}): Promise<unknown> {
    return this.invoke("protocol", args, opts) as Promise<unknown>
  }

  /**
   * One recipe, with its source. `GET /v1/recipes/{name}`.
   */
  recipeGet(args: { name: string }, opts: CallOptions = {}): Promise<unknown> {
    return this.invoke("recipe_get", args, opts) as Promise<unknown>
  }

  /**
   * Run a recipe with its placeholders filled in. `POST /v1/recipes/{name}/run`.
   */
  recipeRun(args: { name: string; placeholders?: Record<string, unknown>; autonomy?: "propose" | "run"; session?: string }, opts: CallOptions = {}): Promise<unknown> {
    return this.invoke("recipe_run", args, opts) as Promise<unknown>
  }

  /**
   * Save a script as a recipe. `POST /v1/recipes/{name}`.
   */
  recipeSave(args: { name: string; source: string; overwrite?: boolean }, opts: CallOptions = {}): Promise<unknown> {
    return this.invoke("recipe_save", args, opts) as Promise<unknown>
  }

  /**
   * Saved scripts, with the placeholders each takes. `GET /v1/recipes`.
   */
  recipesList(args: { q?: string; limit?: number } = {}, opts: CallOptions = {}): Promise<unknown> {
    return this.invoke("recipes_list", args, opts) as Promise<unknown>
  }

  /**
   * Re-read the configuration and every server's schemas. `POST /v1/refresh`.
   * Privileged: it changes the daemon rather than reading it.
   */
  refresh(args: Record<string, never> = {}, opts: CallOptions = {}): Promise<unknown> {
    return this.invoke("refresh", args, opts) as Promise<unknown>
  }

  /**
   * Search a public registry of MCP servers. `GET /v1/registry/search`.
   */
  registrySearch(args: { q: string; limit?: number }, opts: CallOptions = {}): Promise<unknown> {
    return this.invoke("registry_search", args, opts) as Promise<unknown>
  }

  /**
   * Re-read the configuration and swap server pools without restarting unchanged servers. `POST /v1/reload`.
   * Privileged: it changes the daemon rather than reading it.
   */
  reload(args: Record<string, never> = {}, opts: CallOptions = {}): Promise<unknown> {
    return this.invoke("reload", args, opts) as Promise<unknown>
  }

  /**
   * Which daemon serves a directory. `GET /v1/resolve`.
   */
  resolve(args: { dir: string }, opts: CallOptions = {}): Promise<unknown> {
    return this.invoke("resolve", args, opts) as Promise<unknown>
  }

  /**
   * Read one resource from one server. `POST /v1/resource`.
   */
  resourceRead(args: { server: string; uri: string; session?: string; context?: Record<string, unknown> }, opts: CallOptions = {}): Promise<unknown> {
    return this.invoke("resource_read", args, opts) as Promise<unknown>
  }

  /**
   * Every templated resource the configured servers offer. `GET /v1/resource-templates`.
   */
  resourceTemplates(args: { ns?: string } = {}, opts: CallOptions = {}): Promise<unknown> {
    return this.invoke("resource_templates", args, opts) as Promise<unknown>
  }

  /**
   * Every resource the configured servers offer. `GET /v1/resources`.
   */
  resources(args: { ns?: string } = {}, opts: CallOptions = {}): Promise<unknown> {
    return this.invoke("resources", args, opts) as Promise<unknown>
  }

  /**
   * Restart a server's instances, or every server's. `POST /v1/restart`.
   * Privileged: it changes the daemon rather than reading it.
   * Destructive: it cannot be undone, and other callers are affected.
   */
  restart(args: { server?: string; lazy?: boolean } = {}, opts: CallOptions = {}): Promise<unknown> {
    return this.invoke("restart", args, opts) as Promise<unknown>
  }

  /**
   * Rank tools against a query. `GET /v1/search`.
   */
  search(args: { q: string; limit?: number; semantic?: boolean }, opts: CallOptions = {}): Promise<unknown> {
    return this.invoke("search", args, opts) as Promise<unknown>
  }

  /**
   * Add a server, live. `POST /v1/servers`.
   * Privileged: it changes the daemon rather than reading it.
   */
  serversAdd(args: { name: string; command?: string; args?: unknown[]; env?: Record<string, unknown>; url?: string; headers?: Record<string, unknown>; transport?: "stdio" | "http" | "sse"; mcpx?: Record<string, unknown>; scope?: "project" | "user"; replace?: boolean }, opts: CallOptions = {}): Promise<unknown> {
    return this.invoke("servers_add", args, opts) as Promise<unknown>
  }

  /**
   * Every configured server as it is written in the configuration. `GET /v1/servers`.
   */
  serversList(args: Record<string, never> = {}, opts: CallOptions = {}): Promise<unknown> {
    return this.invoke("servers_list", args, opts) as Promise<unknown>
  }

  /**
   * Remove a server, live. `DELETE /v1/servers/{name}`.
   * Privileged: it changes the daemon rather than reading it.
   * Destructive: it cannot be undone, and other callers are affected.
   */
  serversRemove(args: { name: string; scope?: "project" | "user" }, opts: CallOptions = {}): Promise<unknown> {
    return this.invoke("servers_remove", args, opts) as Promise<unknown>
  }

  /**
   * Free the instances a finished caller created. `POST /v1/session/release`.
   * Privileged: it changes the daemon rather than reading it.
   */
  sessionRelease(args: { session: string }, opts: CallOptions = {}): Promise<unknown> {
    return this.invoke("session_release", args, opts) as Promise<unknown>
  }

  /**
   * One setting. `GET /v1/settings/{path}`.
   */
  settingsGet(args: { path: string }, opts: CallOptions = {}): Promise<unknown> {
    return this.invoke("settings_get", args, opts) as Promise<unknown>
  }

  /**
   * Every setting, its effective value and where that value came from. `GET /v1/settings`.
   */
  settingsList(args: { scope?: "daemon" | "client" | "call" | "plugin"; plumbing?: "0" | "1"; changed?: "0" | "1" } = {}, opts: CallOptions = {}): Promise<unknown> {
    return this.invoke("settings_list", args, opts) as Promise<unknown>
  }

  /**
   * Change a setting. `PUT /v1/settings/{path}`.
   * Privileged: it changes the daemon rather than reading it.
   */
  settingsSet(args: { path: string; value: string; persist?: "runtime" | "project" | "user" }, opts: CallOptions = {}): Promise<unknown> {
    return this.invoke("settings_set", args, opts) as Promise<unknown>
  }

  /**
   * Drop a runtime override. `DELETE /v1/settings/{path}`.
   * Privileged: it changes the daemon rather than reading it.
   */
  settingsUnset(args: { path: string }, opts: CallOptions = {}): Promise<unknown> {
    return this.invoke("settings_unset", args, opts) as Promise<unknown>
  }

  /**
   * Stop the daemon. `POST /v1/shutdown`.
   * Privileged: it changes the daemon rather than reading it.
   * Destructive: it cannot be undone, and other callers are affected.
   */
  shutdown(args: Record<string, never> = {}, opts: CallOptions = {}): Promise<unknown> {
    return this.invoke("shutdown", args, opts) as Promise<unknown>
  }

  /**
   * Aggregate the log into numbers. `GET /v1/stats`.
   */
  statsQuery(args: { by?: "calls" | "servers" | "instances" | "errors" | "sessions" | "volume" | "slowest"; since?: string; until?: string; server?: string; tool?: string; session?: string; top?: number } = {}, opts: CallOptions = {}): Promise<unknown> {
    return this.invoke("stats_query", args, opts) as Promise<unknown>
  }

  /**
   * The daemon, its pools and live instances. `GET /v1/status`.
   */
  status(args: Record<string, never> = {}, opts: CallOptions = {}): Promise<unknown> {
    return this.invoke("status", args, opts) as Promise<unknown>
  }

  /**
   * Cancel a running task. `POST /v1/tasks/{id}/cancel`.
   */
  taskCancel(args: { id: string }, opts: CallOptions = {}): Promise<unknown> {
    return this.invoke("task_cancel", args, opts) as Promise<unknown>
  }

  /**
   * One task's status. `GET /v1/tasks/{id}`.
   */
  taskGet(args: { id: string }, opts: CallOptions = {}): Promise<unknown> {
    return this.invoke("task_get", args, opts) as Promise<unknown>
  }

  /**
   * Wait for a task and collect its result. `GET /v1/tasks/{id}/result`.
   */
  taskResult(args: { id: string; waitMs?: number }, opts: CallOptions = {}): Promise<unknown> {
    return this.invoke("task_result", args, opts) as Promise<unknown>
  }

  /**
   * Background calls and their status. `GET /v1/tasks`.
   */
  tasksList(args: Record<string, never> = {}, opts: CallOptions = {}): Promise<unknown> {
    return this.invoke("tasks_list", args, opts) as Promise<unknown>
  }

  /**
   * Run one of mcpx's own MCP tools as a plain POST. `POST /v1/tools/{tool}`.
   */
  toolInvoke(args: { tool: string; arguments?: Record<string, unknown> }, opts: CallOptions = {}): Promise<unknown> {
    return this.invoke("tool_invoke", args, opts) as Promise<unknown>
  }

  /**
   * Every tool of every configured server. `GET /v1/tools`.
   */
  tools(args: { ns?: string } = {}, opts: CallOptions = {}): Promise<unknown> {
    return this.invoke("tools", args, opts) as Promise<unknown>
  }

  /**
   * TypeScript declarations for the named namespaces. `GET /v1/types`.
   */
  types(args: { ns?: string; instructions?: "0" | "1"; profile?: string; skipDefault?: "0" | "1"; allProfiles?: "0" | "1" } = {}, opts: CallOptions = {}): Promise<Response> {
    return this.invoke("types", args, opts) as Promise<Response>
  }
}
