apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apisix
  namespace: argocd
spec:
  project: testing-apisix
  source:
    repoURL: https://github.com/developing-today/code
    path: manifests/apisix
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
        - overlays/testing/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: testing-apisix
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
# kubectl apply -f apisix-app.yaml -n argocd
