apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: testing
  namespace: argocd
spec:
  description: "Project for APISIX testing"
  sourceRepos:
    - https://github.com/developing-today/code
  destinations:
    - namespace: testing
      server: https://kubernetes.default.svc
    - namespace: argocd
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
# kubectl apply -f testing-project.yaml
