apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: piraeus-datastore
resources:
  - https://github.com/piraeusdatastore/piraeus-operator//config/default?ref=v2.7.1
  - linstor-cluster.yaml # should this be after linstor-satellite-configuration?
  - linstor-satellite-configuration.yaml # should this be before linstor-cluster?
  - pv-medium-nvme-test.yaml
  - pvc-medium-nvme-test.yaml
