apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: medium-nvme-immediate-test-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi
  storageClassName: linstor-medium-nvme-immediate
