apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: drbd-medium-nvme-test
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20G
  volumeName: drbd-medium-nvme-test
  storageClassName: piraeus-storage
