name: goreleaser

on:
  push:
  #   tags:
  #     - '*'
  pull_request:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  goreleaser:
    name: ${{ matrix }} goreleaser
    strategy:
      matrix:
        includes: [ "./sources/graph" ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: "${{ matrix }}/go.mod"
          check-latest: true
      - name: Run GoReleaser ${{ matrix }}
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
          workdir: ${{ matrix }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
