PROJECT_NAME=provider
PROJECT_DIR="$(pwd)"

if [[ -z "$BACKGROUND_JOB_DIR" ]]; then
  BACKGROUND_JOB_DIR="$PROJECT_DIR/background"
fi
if [[ -z "$BACKGROUND_JOB_EXECUTING_DIR" ]]; then
  BACKGROUND_JOB_EXECUTING_DIR="$BACKGROUND_JOB_DIR/executing"
fi
if [[ -z "$BACKGROUND_JOB_COMPLETE_DIR" ]]; then
  BACKGROUND_JOB_COMPLETE_DIR="$BACKGROUND_JOB_DIR/complete"
fi
if [[ -z "$BACKGROUND_JOB_FAILED_DIR" ]]; then
  BACKGROUND_JOB_FAILED_DIR="$BACKGROUND_JOB_DIR/failed"
fi
